/**
 * Clinical Calendar Export Service (v5.3)
 * Generates standards-compliant .ics files from clinical timeline data.
 */

// Helper to format date to YYYYMMDD
const formatICSDate = (date) => {
  const d = new Date(date);
  return d.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
};

// Helper to format date to YYYYMMDD (all day)
const formatICSDateAllDay = (date) => {
  const d = new Date(date);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}${m}${day}`;
};

/**
 * Generates the raw ICS string for a protocol.
 * Optimized for both direct download and Webcal feeds.
 */
export const serializeProtocolToICS = (protocolData) => {
  const { protocol_title, protocol_id, _timeline } = protocolData;
  const timeline = _timeline || [];
  
  const title = protocol_title || 'Clinical Protocol';
  const id = protocol_id || 'REGEN-PROT-01';

  let icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ReGen PEPT//Clinical Calendar v5.4//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:Dosing Schedule - ${title}`,
    'X-WR-CALDESC:Clinical dosing protocol generated by ReGen PEPT',
    'X-WR-TIMEZONE:UTC',
    'X-PUBLISHED-TTL:P1D', // Suggest 1 day refresh for subscriptions
    'REFRESH-INTERVAL;VALUE=DURATION:P1D'
  ];

  // Process timeline events
  const generateEvents = () => {
    const events = [];
    if (!timeline.length) return "";

    timeline.forEach((week) => {
      const weekMeds = week.medications || (week.events ? week.events.filter(e => e.type === 'medication').map(e => ({
        compound: e.name || e.compound,
        dose: e.dosage || e.dose || 'Standard',
        day: (e.days && e.days.length) ? e.days[0] : 'Monday'
      })) : []);
      const startDate = new Date(week.startDate || new Date());
      
      weekMeds.forEach((med, mIdx) => {
        // Map day to offset
        const daysMap = { 'Monday': 0, 'Tuesday': 1, 'Wednesday': 2, 'Thursday': 3, 'Friday': 4, 'Saturday': 5, 'Sunday': 6 };
        const dayOffset = daysMap[med.day] || 0;
        const eventDate = new Date(startDate);
        eventDate.setDate(eventDate.getDate() + dayOffset);
        
        const dtStr = formatICSDateAllDay(eventDate);
        const stamp = formatICSDate(new Date());
        
        events.push([
          'BEGIN:VEVENT',
          `UID:${id}-W${week.week}-M${mIdx}-${dtStr}@regen-pept.com`,
          `DTSTAMP:${stamp}`,
          `DTSTART;VALUE=DATE:${dtStr}`,
          `DTEND;VALUE=DATE:${dtStr}`,
          `SUMMARY:Injection: ${med.compound} (${med.dose})`,
          `DESCRIPTION:Protocol: ${title}\\nWeek: ${week.week}\\nCompound: ${med.compound}\\nDosage: ${med.dose}\\n\\nINSTRUCTIONS: Administer subcutaneous injection as directed in the protocol guidelines.`,
          'STATUS:CONFIRMED',
          'TRANSP:TRANSPARENT',
          'CATEGORIES:Clinical,Medication',
          'BEGIN:VALARM',
          'TRIGGER:-P1D', // 1 day before
          'ACTION:DISPLAY',
          'DESCRIPTION:Dosing Reminder (1 Day)',
          'END:VALARM',
          'BEGIN:VALARM',
          'TRIGGER:-PT1H', // 1 hour before
          'ACTION:DISPLAY',
          'DESCRIPTION:Dosing Reminder (1 Hour)',
          'END:VALARM',
          'BEGIN:VALARM',
          'TRIGGER:-PT15M', // 15 minutes before
          'ACTION:DISPLAY',
          'DESCRIPTION:URGENT: Dosing Time (15m)',
          'END:VALARM',
          'END:VEVENT'
        ].join('\r\n'));
      });
    });

    return events.join('\r\n');
  };

  const eventContent = generateEvents();
  if (eventContent) {
    icsLines.push(eventContent);
  }

  icsLines.push('END:VCALENDAR');

  return icsLines.join('\r\n');
};

/**
 * Standard download function
 */
export const generateProtocolICS = (protocolData) => {
  const fullICS = serializeProtocolToICS(protocolData);
  const id = protocolData.protocol_id || 'REGEN-PROT-01';
  
  // Download implementation
  const blob = new Blob([fullICS], { type: 'text/calendar;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `Dosing_Schedule_${id}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

/**
 * Generates a Webcal subscription URL
 * Note: Requires backend support for persistent storage of protocol IDs
 */
export const getWebcalUrl = (protocolId) => {
  return `webcal://api.regen-pept.com/calendar/v1/feed/${protocolId}.ics`;
};

/**
 * Returns a link to import into Google Calendar
 */
export const getGoogleCalendarImportUrl = () => {
  return "https://calendar.google.com/calendar/r/settings/export";
};
