/**
 * seedFagronNutriGenProducts.mjs
 * 
 * Normalizes and associates canonical products for Fagron Genomics NutriGen
 * using Fagron Iberia as supplier. Adheres strictly to the multi-program
 * Product ↔ Program Association architecture with idempotent deduplication.
 */
import { adminDb } from '../lib/firebaseAdmin.js';

if (!adminDb) {
  console.error('Firebase Admin not initialized');
  process.exit(1);
}

const NUTRIGEN_PROGRAM_ID = 'fagron-genomics-nutrigen';
const NUTRIGEN_PROGRAM_NAME = 'Fagron Genomics | NutriGen';
const NUTRIGEN_SLUG = 'fagron-genomics-nutrigen';
const FAGRON_IBERIA_SUPPLIER_ID = 'supplier-fagron-iberia';
const FAGRON_IBERIA_SUPPLIER_NAME = 'Fagron Iberia';

const NUTRIGEN_PRODUCTS = [
  // ── PRIORITY A ─────────────────────────────────────────────────────────────
  {
    canonicalSlug: 'vitamin-d3',
    name: 'Vitamin D3 (Cholecalciferol Pure API)',
    canonicalName: 'Vitamin D3 (Cholecalciferol)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential secosteroid hormone modulating over 200 genes related to immune response, calcium homeostasis, and metabolic health.',
    commercialName: 'Cholecalciferol 100,000 IU/g / Pure Powder',
    synonyms: ['Vitamin D3', 'Cholecalciferol', 'Colecalciferol', 'Vitamin D'],
    dosage: '1,000 IU - 5,000 IU',
    format: 'Bulk Powder / Oily Solution',
    purity: 'Pharma Grade',
    casNumber: '67-97-0',
    tags: ['Immunity', 'Gene Modulation', 'Metabolic Health', 'Bone Density']
  },
  {
    canonicalSlug: 'resveratrol',
    name: 'Trans-Resveratrol 98% (Polygonum cuspidatum)',
    canonicalName: 'Resveratrol',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Potent natural stilbenoid polyphenol and SIRT1 sirtuin activator promoting mitochondrial biogenesis and metabolic efficiency.',
    commercialName: 'Trans-Resveratrol 98% API',
    synonyms: ['Resveratrol', 'Trans-Resveratrol', 'Polygonum cuspidatum extract'],
    dosage: '100 mg - 500 mg',
    format: 'Bulk Powder (98% Trans-Resveratrol)',
    purity: '≥98%',
    casNumber: '501-36-0',
    tags: ['Sirtuin Activator', 'Mitochondria', 'Metabolic Health', 'Polyphenol']
  },
  {
    canonicalSlug: 'magnesium',
    name: 'Magnesium (Bisglycinate / Citrate / Malate)',
    canonicalName: 'Magnesium',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Crucial macromineral cofactor for >300 enzymatic reactions including ATP production, glycolysis, DNA/RNA synthesis, and neuromuscular transmission.',
    commercialName: 'Magnesium Bisglycinate Chelate 20% / Citrate API',
    synonyms: ['Magnesium', 'Magnesium Bisglycinate', 'Magnesium Citrate', 'Magnesium Malate'],
    dosage: '200 mg - 400 mg elemental Mg',
    format: 'Bulk Powder',
    purity: 'Pharma Grade',
    casNumber: '7439-95-4',
    tags: ['Essential Mineral', 'Enzyme Cofactor', 'ATP Synthesis', 'Neuromuscular']
  },
  {
    canonicalSlug: 'riboflavin',
    name: 'Vitamin B2 (Riboflavin / Riboflavin-5-Phosphate)',
    canonicalName: 'Vitamin B2 (Riboflavin)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Precursor of flavin coenzymes FMN and FAD involved in mitochondrial electron transport, fatty acid beta-oxidation, and MTHFR cycle.',
    commercialName: 'Riboflavin / Riboflavin-5-Phosphate Sodium API',
    synonyms: ['Vitamin B2', 'Riboflavin', 'Riboflavine', 'R-5-P', 'Vit B2'],
    dosage: '25 mg - 100 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥98%',
    casNumber: '83-88-5',
    tags: ['Mitochondrial Respiration', 'FAD Cofactor', 'MTHFR Pathway', 'B-Complex']
  },
  {
    canonicalSlug: 'taurine',
    name: 'Taurine Pure API (2-Aminoethanesulfonic Acid)',
    canonicalName: 'Taurine',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Conditionally essential amino sulfonic acid key for bile acid conjugation, osmoregulation, membrane stabilization, and mitochondrial function.',
    commercialName: 'Taurine Pure API USP',
    synonyms: ['Taurine', '2-Aminoethanesulfonic Acid', 'L-Taurine'],
    dosage: '500 mg - 2000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '107-35-7',
    tags: ['Bile Acid Conjugation', 'Osmoregulation', 'Mitochondrial Health', 'Cardiovascular']
  },
  {
    canonicalSlug: 'niacin',
    name: 'Niacin (Nicotinic Acid API)',
    canonicalName: 'Niacin (Nicotinic Acid)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Pure nicotinic acid supporting lipid metabolism, HDL elevation, and serving as fundamental substrate for cellular NAD+/NADP+ pools.',
    commercialName: 'Nicotinic Acid / Niacin USP',
    synonyms: ['Niacin', 'Nicotinic Acid', 'Vitamin B3 Acid'],
    dosage: '50 mg - 500 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '59-67-6',
    tags: ['Lipid Regulation', 'NAD+ Substrate', 'Cardiovascular', 'B-Complex']
  },
  {
    canonicalSlug: 'vitamin-k2',
    name: 'Vitamin K2 (Menaquinone-7 / MK-7)',
    canonicalName: 'Vitamin K2',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Natural menaquinone-7 directing calcium away from arterial walls into bone matrix via osteocalcin and matrix Gla-protein (MGP) carboxylation.',
    commercialName: 'Menaquinone-7 (MK-7) 2000 ppm / Pure Powder',
    synonyms: ['Vitamin K2', 'Menaquinone-7', 'MK-7', 'Menaquinone', 'Vit K2'],
    dosage: '100 mcg - 200 mcg',
    format: 'Bulk Powder (Standardized MK-7)',
    purity: 'Pharma Grade',
    casNumber: '2124-57-4',
    tags: ['Arterial Health', 'Calcium Metabolism', 'Bone Density', 'Vascular Protection']
  },
  {
    canonicalSlug: 'vitamin-b12',
    name: 'Vitamin B12 (Methylcobalamin / Cyanocobalamin)',
    canonicalName: 'Vitamin B12',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential cobalamin cofactor for methionine synthase (homocysteine remethylation) and methylmalonyl-CoA mutase (energy production).',
    commercialName: 'Methylcobalamin / Cyanocobalamin 1% & Pure API',
    synonyms: ['Vitamin B12', 'Methylcobalamin', 'Cyanocobalamin', 'Cobalamin', 'Cianocobalamin', 'Vit B12'],
    dosage: '500 mcg - 1000 mcg',
    format: 'Bulk Powder (1% / Pure)',
    purity: '≥98%',
    casNumber: '13422-55-4',
    tags: ['Methylation', 'Homocysteine Regulation', 'Neurological', 'Erythropoiesis']
  },
  {
    canonicalSlug: 'biotin',
    name: 'D-Biotin Pure API (Vitamin B7 / Vitamin H)',
    canonicalName: 'Biotin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential cofactor for carboxylase enzymes mediating fatty acid elongation, amino acid catabolism, and gluconeogenesis.',
    commercialName: 'D-Biotin Pure API USP',
    synonyms: ['Biotin', 'D-Biotin', 'Vitamin B7', 'Vitamin H'],
    dosage: '2.5 mg - 10 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '58-85-5',
    tags: ['Carboxylase Cofactor', 'Gluconeogenesis', 'Lipid Synthesis', 'Metabolism']
  },
  {
    canonicalSlug: 'nicotinamide',
    name: 'Nicotinamide / Niacinamide (Vitamin B3)',
    canonicalName: 'Nicotinamide (Niacinamide)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Non-flushing Vitamin B3 derivative directly converted to nicotinamide mononucleotide (NMN) and NAD+, supporting mitochondrial bioenergetics.',
    commercialName: 'Niacinamide / Nicotinamide USP',
    synonyms: ['Nicotinamide', 'Niacinamide', 'Vitamin B3', 'Vit B3'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '98-92-0',
    tags: ['NAD+ Synthesis', 'Sirtuin Cofactor', 'Mitochondrial Energy', 'Cellular Repair']
  },
  {
    canonicalSlug: 'zinc-gluconate',
    name: 'Zinc Gluconate Pure API',
    canonicalName: 'Zinc Gluconate',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Highly tolerable organic zinc salt ensuring optimal metalloenzyme activity, gustatory perception, insulin storage, and immune resilience.',
    commercialName: 'Zinc Gluconate USP / Food Grade',
    synonyms: ['Zinc Gluconate', 'Zinc D-gluconate'],
    dosage: '15 mg - 30 mg elemental Zn',
    format: 'Bulk Powder',
    purity: '≥98%',
    casNumber: '4468-02-4',
    tags: ['Metalloenzymes', 'Insulin Cofactor', 'Immunity', 'Trace Mineral']
  },
  {
    canonicalSlug: 'n-acetylcysteine',
    name: 'N-Acetyl-L-Cysteine (NAC Pure API)',
    canonicalName: 'Acetylcysteine (N-Acetylcysteine / NAC)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Rate-limiting direct precursor to intracellular reduced glutathione (GSH), providing essential sulfur groups for Phase II hepatic detoxification.',
    commercialName: 'N-Acetylcysteine (NAC) Pure USP',
    synonyms: ['Acetylcysteine', 'N-Acetylcysteine', 'NAC', 'N-Acetyl-L-Cysteine'],
    dosage: '600 mg - 1200 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '616-91-1',
    tags: ['Glutathione Precursor', 'Hepatic Detoxification', 'Phase II Conjugation', 'Mucolytic']
  },
  {
    canonicalSlug: 'pyridoxine-hcl',
    name: 'Pyridoxine Hydrochloride (Vitamin B6)',
    canonicalName: 'Vitamin B6 (Pyridoxine Hydrochloride)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Active precursor to pyridoxal-5-phosphate (PLP), cofactor for >140 decarboxylase, transaminase, and transsulfuration enzymes.',
    commercialName: 'Pyridoxine HCl USP',
    synonyms: ['Vitamin B6', 'Pyridoxine HCl', 'Pyridoxine Hydrochloride', 'Vit B6'],
    dosage: '25 mg - 50 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '58-56-0',
    tags: ['PLP Cofactor', 'Amino Acid Metabolism', 'Transsulfuration', 'Neurotransmitter']
  },
  {
    canonicalSlug: 'thiamine-hcl',
    name: 'Thiamine Hydrochloride (Vitamin B1)',
    canonicalName: 'Vitamin B1 (Thiamine Hydrochloride)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential precursor to thiamine pyrophosphate (TPP), critical cofactor for pyruvate dehydrogenase and alpha-ketoglutarate dehydrogenase in the Krebs cycle.',
    commercialName: 'Thiamine HCl USP',
    synonyms: ['Vitamin B1', 'Thiamine HCl', 'Thiamine Hydrochloride', 'Aneurine', 'Vit B1'],
    dosage: '50 mg - 100 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '67-03-8',
    tags: ['Krebs Cycle', 'Pyruvate Dehydrogenase', 'Glucose Metabolism', 'B-Complex']
  },
  {
    canonicalSlug: 'selenium-yeast',
    name: 'Selenium Yeast (Organic Selenomethionine)',
    canonicalName: 'Selenium (Selenium Yeast)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized organically bound selenium yeast supporting selenoproteins, glutathione peroxidase, and iodothyronine deiodinase activity.',
    commercialName: 'Selenium Yeast 2000 ppm',
    synonyms: ['Selenium Yeast', 'Organic Selenium', 'Selenomethionine Yeast', 'Selenium'],
    dosage: '100 mcg - 200 mcg Se',
    format: 'Bulk Powder',
    purity: '2000 ppm Se',
    casNumber: '',
    tags: ['Selenoproteins', 'Glutathione Peroxidase', 'Thyroid Conversion', 'Antioxidant']
  },
  {
    canonicalSlug: 'glucosamine-sulfate',
    name: 'D-Glucosamine Sulfate 2KCl',
    canonicalName: 'Glucosamine Sulfate',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Key building block for glycosaminoglycans and proteoglycans in articular cartilage, stabilizing joint matrix and supporting intestinal mucosal lining.',
    commercialName: 'Glucosamine Sulfate Potassium Chloride USP',
    synonyms: ['Glucosamine Sulfate', 'D-Glucosamine Sulfate', 'Glucosamine 2KCl'],
    dosage: '1500 mg',
    format: 'Bulk Powder',
    purity: '≥98%',
    casNumber: '31284-96-5',
    tags: ['Cartilage Matrix', 'Proteoglycans', 'Joint Support', 'Mucosal Barrier']
  },
  {
    canonicalSlug: 'ginseng-extract',
    name: 'Panax Ginseng Root Extract (Ginsenosides)',
    canonicalName: 'Ginseng Dry Extract (Panax ginseng)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized Panax ginseng extract improving insulin sensitivity, hypothalamic-pituitary-adrenal (HPA) axis balance, and physical endurance.',
    commercialName: 'Panax Ginseng Extract 20%',
    synonyms: ['Ginseng', 'Panax Ginseng', 'Ginseng Dry Extract', 'Korean Ginseng'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥20% Ginsenosides',
    casNumber: '90045-38-8',
    tags: ['Adaptogen', 'Insulin Sensitivity', 'HPA Axis', 'Endurance']
  },
  {
    canonicalSlug: 'vitamin-c',
    name: 'Vitamin C (Ascorbic Acid Pure API)',
    canonicalName: 'Vitamin C (Ascorbic Acid)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Primary water-soluble antioxidant, essential cofactor for prolyl and lysyl hydroxylases in collagen biosynthesis, and iron absorption enhancer.',
    commercialName: 'L-Ascorbic Acid USP / Ph. Eur.',
    synonyms: ['Vitamin C', 'Ascorbic Acid', 'L-Ascorbic Acid', 'Vit C'],
    dosage: '500 mg - 1000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99.5%',
    casNumber: '50-81-7',
    tags: ['Antioxidant', 'Collagen Biosynthesis', 'Iron Absorption', 'Immune Support']
  },
  {
    canonicalSlug: 'glutathione',
    name: 'Reduced L-Glutathione (GSH Pure API)',
    canonicalName: 'Glutathione (Reduced Glutathione)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'The body\'s master intracellular antioxidant and primary Phase II conjugation agent for xenobiotics, heavy metals, and lipid peroxides.',
    commercialName: 'Reduced L-Glutathione (GSH) Pure API',
    synonyms: ['Glutathione', 'Reduced Glutathione', 'L-Glutathione', 'GSH'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥98%',
    casNumber: '70-18-8',
    tags: ['Master Antioxidant', 'Phase II Conjugation', 'Detoxification', 'Mitochondria']
  },
  {
    canonicalSlug: 'l-glutamine',
    name: 'L-Glutamine Pure API (Levoglutamine)',
    canonicalName: 'Glutamine (Levoglutamine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Primary metabolic fuel for enterocytes and immune cells, supporting intestinal tight junctions, gut mucosal integrity, and nitrogen balance.',
    commercialName: 'L-Glutamine (Levoglutamine) Pure USP',
    synonyms: ['Glutamine', 'L-Glutamine', 'Levoglutamine'],
    dosage: '2000 mg - 5000 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '56-85-9',
    tags: ['Enterocyte Fuel', 'Intestinal Permeability', 'Gut Mucosa', 'Nitrogen Balance']
  },
  {
    canonicalSlug: 'vitamin-e',
    name: 'Vitamin E (Tocopherol API)',
    canonicalName: 'Vitamin E',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Major lipid-soluble antioxidant intercepting peroxyl radicals in membrane phospholipids and protecting against lipid peroxidation.',
    commercialName: 'd-alpha-Tocopherol / dl-alpha-Tocopheryl Acetate',
    synonyms: ['Vitamin E', 'Tocopherol', 'd-alpha-tocopherol', 'vit, E'],
    dosage: '400 IU / 268 mg',
    format: 'Bulk Powder / Oil',
    purity: '≥98%',
    casNumber: '59-02-9',
    tags: ['Lipid Antioxidant', 'Membrane Stability', 'Cardiovascular', 'Vitamin']
  },
  {
    canonicalSlug: 'melatonin',
    name: 'Melatonin Pure API',
    canonicalName: 'Melatonin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Neurohormone synchronizing circadian rhythms, regulating mitochondrial redox state, and modulating nocturnal glucose tolerance.',
    commercialName: 'Melatonin Pure API USP',
    synonyms: ['Melatonin', 'N-acetyl-5-methoxytryptamine'],
    dosage: '1 mg - 5 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99.5%',
    casNumber: '73-31-4',
    tags: ['Circadian Synchronization', 'Mitochondrial Redox', 'Sleep Architecture', 'Antioxidant']
  },
  {
    canonicalSlug: 'retinol-vitamin-a',
    name: 'Vitamin A (Retinol / Retinyl Acetate)',
    canonicalName: 'Vitamin A',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential fat-soluble vitamin for visual cycle rhodopsin regeneration, epithelial barrier differentiation, and mucosal immunity.',
    commercialName: 'Retinyl Acetate / Palmitate 500,000 IU/g',
    synonyms: ['Vitamin A', 'Retinol', 'Retinyl Acetate', 'Retinyl Palmitate', 'Vit A'],
    dosage: '2500 IU - 5000 IU',
    format: 'Bulk Powder / Oil',
    purity: 'Pharma Grade',
    casNumber: '68-26-8',
    tags: ['Epithelial Differentiation', 'Mucosal Immunity', 'Vision', 'Vitamin']
  },
  {
    canonicalSlug: 'valerian-extract',
    name: 'Valerian Root Dry Extract (Valeriana officinalis)',
    canonicalName: 'Valerian Dry Extract (Valeriana officinalis)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized Valeriana officinalis extract rich in valerenic acids, allosterically modulating GABA-A receptors and easing nervous tension.',
    commercialName: 'Valerian Dry Extract 0.8% Valerenic Acid',
    synonyms: ['Valerian', 'Valerian Root Extract', 'Valeriana officinalis', 'Valerian Dry Extract'],
    dosage: '300 mg - 600 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥0.8% Valerenic Acid',
    casNumber: '8057-49-6',
    tags: ['GABAergic Modulation', 'Sleep Latency', 'Stress Relief', 'Phytotherapy']
  },
  {
    canonicalSlug: 'l-methionine',
    name: 'L-Methionine Pure API',
    canonicalName: 'Methionine',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential sulfur amino acid required for SAMe synthesis (universal methyl donor) and precursor for homocysteine, cysteine, and glutathione.',
    commercialName: 'L-Methionine Pure USP',
    synonyms: ['Methionine', 'L-Methionine'],
    dosage: '500 mg - 1000 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '63-68-3',
    tags: ['SAMe Precursor', 'Methyl Donor', 'Sulfur Metabolism', 'Lipomerism']
  },
  {
    canonicalSlug: 'siliciumax',
    name: 'SiliciuMax® Powder (Organic Silicon)',
    canonicalName: 'SiliciuMax® Powder',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Bioavailable organic silicon powder stimulating osteoblasts, collagen synthesis, and arterial elasticity.',
    commercialName: 'SiliciuMax® Powder',
    synonyms: ['SiliciuMax', 'SiliciuMax®', 'SiliciuMax Powder', 'Organic Silicon'],
    dosage: '10 mg - 20 mg elemental Si',
    format: 'Bulk Powder',
    purity: 'Patented Bioavailable Silicon',
    casNumber: '',
    tags: ['Collagen Cross-Linking', 'Connective Tissue', 'Arterial Elasticity', 'Silicon']
  },
  {
    canonicalSlug: 'methylfolate',
    name: 'Vitamin B9 (L-Methylfolate / 5-MTHF Calcium)',
    canonicalName: 'Vitamin B9 (Methylfolate)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Active, biologically active form of folate bypassing MTHFR genetic polymorphisms for immediate entry into the one-carbon methylation cycle.',
    commercialName: 'L-5-Methyltetrahydrofolate Calcium (5-MTHF) API',
    synonyms: ['Methylfolate', '5-MTHF', 'L-Methylfolate', 'Vitamin B9', 'Folic Acid Active', 'Vit B9'],
    dosage: '400 mcg - 1000 mcg',
    format: 'Bulk Crystalline Powder',
    purity: '≥98%',
    casNumber: '151533-22-1',
    tags: ['Active Methylation', 'MTHFR Bypass', 'Homocysteine Lowering', 'DNA Synthesis']
  },
  {
    canonicalSlug: 'bifidobacterium-adolescentis',
    name: 'Bifidobacterium adolescentis (Probiotic Strain)',
    canonicalName: 'Bifidobacterium adolescentis',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Key human gut colonizer producing acetate and lactate, modulating gut motility, and producing B-vitamins and GABA.',
    commercialName: 'Bifidobacterium adolescentis Freeze-Dried 100B CFU/g',
    synonyms: ['B. adolescentis', 'Bifidobacterium adolescentis'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Probiotic Strain', 'Short Chain Fatty Acids', 'Microbiome Balance', 'GABA Producer']
  },
  {
    canonicalSlug: 'bifidobacterium-infantis',
    name: 'Bifidobacterium infantis (Probiotic Strain)',
    canonicalName: 'Bifidobacterium infantis',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Beneficial probiotic strain specialized in human milk oligosaccharide (HMO) breakdown, strengthening tight junctions and downregulating pro-inflammatory cytokines.',
    commercialName: 'Bifidobacterium infantis 100B CFU/g',
    synonyms: ['B. infantis', 'Bifidobacterium infantis'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Probiotic Strain', 'Gut Barrier', 'Anti-Inflammatory', 'Infant Microbiome']
  },
  {
    canonicalSlug: 'bifidobacterium-longum',
    name: 'Bifidobacterium longum (Probiotic Strain)',
    canonicalName: 'Bifidobacterium longum',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Resilient human commensal strain fermenting diverse carbohydrates to produce butyrate precursors, promoting gut-brain axis calm.',
    commercialName: 'Bifidobacterium longum 100B CFU/g',
    synonyms: ['B. longum', 'Bifidobacterium longum'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Probiotic Strain', 'Gut-Brain Axis', 'Butyrate Support', 'Immunomodulation']
  },
  {
    canonicalSlug: 'lactobacillus-lactis',
    name: 'Lactococcus lactis (Probiotic Strain)',
    canonicalName: 'Lactobacillus lactis',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Lactic acid bacterium producing nisin and antimicrobial peptides that inhibit pathogenic bacterial expansion.',
    commercialName: 'Lactococcus lactis 100B CFU/g',
    synonyms: ['Lactobacillus lactis', 'Lactococcus lactis', 'L. lactis'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Probiotic Strain', 'Antimicrobial Nisin', 'Lactic Acid', 'Pathogen Inhibition']
  },
  {
    canonicalSlug: 'lactobacillus-plantarum',
    name: 'Lactobacillus plantarum (Probiotic Strain)',
    canonicalName: 'Lactobacillus plantarum',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Versatile probiotic strain reducing intestinal permeability (leaky gut), degrading biogenic amines, and surviving gastric transit.',
    commercialName: 'Lactobacillus plantarum 100B CFU/g',
    synonyms: ['L. plantarum', 'Lactobacillus plantarum'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Tight Junction Integrity', 'Histamine Clearance', 'Probiotic Strain', 'Gastric Resilience']
  },
  {
    canonicalSlug: 'lactobacillus-salivarius',
    name: 'Lactobacillus salivarius (Probiotic Strain)',
    canonicalName: 'Lactobacillus salivarius',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Fast-growing probiotic colonizing oral and intestinal mucosa, producing bacteriocins to suppress Helicobacter pylori and pathogenic anaerobes.',
    commercialName: 'Lactobacillus salivarius 100B CFU/g',
    synonyms: ['L. salivarius', 'Lactobacillus salivarius'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Oral & Intestinal Mucosa', 'Bacteriocin Producer', 'Probiotic Strain', 'Immune Support']
  },
  {
    canonicalSlug: 'ubiquinol',
    name: 'Ubiquinol (Active Reduced CoQ10)',
    canonicalName: 'Ubiquinol',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Biologically active, pre-reduced form of Coenzyme Q10 providing direct antioxidant capacity and up to 8x higher plasma bioavailability.',
    commercialName: 'Ubiquinol Pure API / Powder',
    synonyms: ['Ubiquinol', 'Reduced CoQ10', 'Active Coenzyme Q10'],
    dosage: '100 mg - 200 mg',
    format: 'Bulk Powder',
    purity: '≥98%',
    casNumber: '992-78-9',
    tags: ['Reduced CoQ10', 'Mitochondrial Bioenergetics', 'High Bioavailability', 'Cardiovascular']
  },
  {
    canonicalSlug: 'mitocondrin',
    name: 'Mitocondrin® (Phytobiotic Mitochondrial Complex)',
    canonicalName: 'Mitocondrin®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'A',
    description: 'Proprietary Fagron mitochondrial support blend activating PGC-1alpha and NRF-2 pathways for enhanced cellular respiration and ATP kinetics.',
    commercialName: 'Mitocondrin®',
    synonyms: ['Mitocondrin', 'Mitocondrin®'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: 'Patented Complex',
    casNumber: '',
    tags: ['Mitochondrial Biogenesis', 'PGC-1alpha', 'NRF-2 Activation', 'Cellular Energy']
  },
  {
    canonicalSlug: 'citrusim',
    name: 'CitrusiM® (Standardized Red Orange Bioflavonoids)',
    canonicalName: 'CitrusiM®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized Sicilian blood orange extract rich in anthocyanins, flavanones, and hydroxycinnamic acids regulating adipogenesis and lipolysis.',
    commercialName: 'CitrusiM®',
    synonyms: ['CitrusiM', 'CitrusiM®', 'Citrus Sinensis Extract'],
    dosage: '400 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: 'Standardized Red Orange Extract',
    casNumber: '',
    tags: ['Adipogenesis Regulation', 'Metabolic Syndrome', 'Anthocyanins', 'Weight Management']
  },
  {
    canonicalSlug: 'brocophanus',
    name: 'Brocophanus® (Standardized Sulforaphane Precursor)',
    canonicalName: 'Brocophanus®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'A',
    description: 'High-yield broccoli seed extract standardized in glucoraphanin and active myrosinase enzyme for optimal in vivo sulforaphane release and Phase II NRF-2 activation.',
    commercialName: 'Brocophanus®',
    synonyms: ['Brocophanus', 'Brocophanus®', 'Glucoraphanin + Myrosinase'],
    dosage: '100 mg - 250 mg',
    format: 'Standardized Powder',
    purity: 'High Glucoraphanin',
    casNumber: '',
    tags: ['Sulforaphane Precursor', 'NRF-2 Inducer', 'Phase II Detox', 'Cellular Protection']
  },
  {
    canonicalSlug: 'cureit',
    name: 'Cureit® (Full-Spectrum Bioavailable Curcumin)',
    canonicalName: 'Cureit®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'A',
    description: 'Complete turmeric matrix (PNS technology) ensuring 10x higher bio-absorption of curcuminoids without requiring piperine.',
    commercialName: 'Cureit®',
    synonyms: ['Cureit', 'Cureit®', 'Bioavailable Curcumin Matrix', 'Curcuma Longa PNS'],
    dosage: '250 mg - 500 mg',
    format: 'Standardized Powder',
    purity: 'Complete Turmeric Matrix',
    casNumber: '',
    tags: ['Full-Spectrum Curcumin', 'High Bioavailability', 'NF-kB Inhibition', 'Anti-Inflammatory']
  },
  {
    canonicalSlug: 'horsetail-extract',
    name: 'Horsetail Dry Extract (Equisetum arvense 7% Silica)',
    canonicalName: 'Horsetail Dry Extract (Equisetum arvense)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized botanical extract naturally rich in soluble bioavailable silicic acid and potassium salts, promoting mild diuresis and remineralization.',
    commercialName: 'Horsetail Dry Extract 7% Silica',
    synonyms: ['Horsetail Extract', 'Equisetum arvense', 'Horsetail Dry Extract'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥7% Silica',
    casNumber: '71011-23-9',
    tags: ['Botanical Silicon', 'Remineralization', 'Connective Tissue', 'Diuretic']
  },
  {
    canonicalSlug: 'black-raphanus-extract',
    name: 'Black Raphanus Dry Extract (Raphanus sativus var. niger)',
    canonicalName: 'Black Raphanus Dry Extract (Raphanus sativus L. var. niger)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Black radish extract containing glucosinolates that stimulate choleresis, bile flow, and hepatic glutathione transferase activity.',
    commercialName: 'Black Radish Dry Extract 4:1',
    synonyms: ['Black Raphanus Extract', 'Raphanus sativus var. niger', 'Black Radish Extract'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Standardized Powder',
    purity: '4:1 Extract',
    casNumber: '84775-94-0',
    tags: ['Choleretic', 'Bile Flow', 'Hepatic Cleansing', 'Glucosinolates']
  },
  {
    canonicalSlug: 'copper-gluconate',
    name: 'Copper Gluconate / Chelate API',
    canonicalName: 'Copper (as Gluconate or Chelate)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential trace mineral required for cytochrome c oxidase (mitochondrial electron transport) and superoxide dismutase (SOD1/SOD3) antioxidant defenses.',
    commercialName: 'Copper Gluconate USP',
    synonyms: ['Copper', 'Copper Gluconate', 'Cooper', 'Copper Bisglycinate'],
    dosage: '1 mg - 2 mg elemental Cu',
    format: 'Bulk Powder',
    purity: 'Pharma Grade',
    casNumber: '527-09-3',
    tags: ['Cytochrome C Oxidase', 'SOD1 Cofactor', 'Iron Metabolism', 'Trace Mineral']
  },
  {
    canonicalSlug: 'manganese-gluconate',
    name: 'Manganese Gluconate / Chelate API',
    canonicalName: 'Manganese',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Cofactor for mitochondrial manganese superoxide dismutase (MnSOD / SOD2) and glycosyltransferases required for cartilage proteoglycan synthesis.',
    commercialName: 'Manganese Gluconate USP',
    synonyms: ['Manganese', 'Manganese Gluconate', 'Manganese Bisglycinate'],
    dosage: '2 mg - 5 mg elemental Mn',
    format: 'Bulk Powder',
    purity: 'Pharma Grade',
    casNumber: '6485-39-8',
    tags: ['MnSOD Cofactor', 'Mitochondrial Protection', 'Proteoglycan Synthesis', 'Trace Mineral']
  },
  {
    canonicalSlug: 'omega-3',
    name: 'Omega-3 Fatty Acids (EPA / DHA Ethyl Esters / Triglycerides)',
    canonicalName: 'Omega 3',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Essential polyunsaturated fatty acids (PUFAs) serving as precursors to specialized pro-resolving mediators (SPMs) and modulating cell membrane fluidity.',
    commercialName: 'Omega-3 Oil EE 50/20 & TG / Microencapsulated Powder',
    synonyms: ['Omega 3', 'Omega-3', 'EPA/DHA', 'Fish Oil Extract'],
    dosage: '1000 mg - 3000 mg EPA/DHA',
    format: 'Bulk Oil / Microencapsulated Powder',
    purity: 'Standardized EPA/DHA',
    casNumber: '',
    tags: ['PUFA', 'Specialized Pro-Resolving Mediators', 'Cardiovascular', 'Cell Membrane']
  },
  {
    canonicalSlug: 'artichoke-extract',
    name: 'Artichoke Leaf Dry Extract (Cynara scolymus 5% Cynarin)',
    canonicalName: 'Artichoke Dry Extract (Cynara scolymus)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Standardized artichoke extract with cynarin and luteolin, stimulating bile acid secretion, liver regeneration, and healthy lipid profiles.',
    commercialName: 'Cynara scolymus Extract 5% Cynarin',
    synonyms: ['Artichoke Extract', 'Cynara scolymus', 'Artichoke Dry Extract'],
    dosage: '300 mg - 600 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥5% Cynarin',
    casNumber: '84012-14-6',
    tags: ['Choleretic', 'Bile Secretion', 'Lipid Metabolism', 'Hepatoprotective']
  },
  {
    canonicalSlug: 'calcium-pantothenate',
    name: 'Calcium D-Pantothenate (Vitamin B5)',
    canonicalName: 'Vitamin B5 (Calcium Pantothenate)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'A',
    description: 'Precursor of Coenzyme A (CoA) and acyl carrier protein (ACP), central to fatty acid synthesis, acetylation reactions, and adrenal steroidogenesis.',
    commercialName: 'Calcium D-Pantothenate USP',
    synonyms: ['Vitamin B5', 'Calcium Pantothenate', 'D-Calcium Pantothenate', 'Vit B5'],
    dosage: '100 mg - 500 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥98%',
    casNumber: '137-08-6',
    tags: ['Coenzyme A Precursor', 'Adrenal Support', 'Acyl Transfer', 'B-Complex']
  },

  // ── PRIORITY B ─────────────────────────────────────────────────────────────
  {
    canonicalSlug: 'bromelain',
    name: 'Bromelain (Ananas comosus 2400 GDU/g)',
    canonicalName: 'Bromelain',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Proteolytic enzyme complex extracted from pineapple stem exhibiting systemic anti-inflammatory, anti-edematous, and fibrinolytic properties.',
    commercialName: 'Bromelain 2400 GDU/g API',
    synonyms: ['Bromelain', 'Ananas comosus enzyme', 'Bromelains'],
    dosage: '500 mg (1200 GDU)',
    format: 'Bulk Powder (2400 GDU/g)',
    purity: '≥2400 GDU/g',
    casNumber: '9001-00-7',
    tags: ['Proteolytic Enzyme', 'Fibrinolytic', 'Anti-Edematous', 'Digestion']
  },
  {
    canonicalSlug: 'l-lysine',
    name: 'L-Lysine Hydrochloride API',
    canonicalName: 'Lysine',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Essential amino acid serving as a substrate for carnitine biosynthesis, collagen cross-linking (lysyl oxidase), and antiviral defense.',
    commercialName: 'L-Lysine HCl USP',
    synonyms: ['Lysine', 'L-Lysine', 'L-Lysine HCl'],
    dosage: '500 mg - 1500 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '657-27-2',
    tags: ['Carnitine Synthesis', 'Collagen Cross-Linking', 'Essential Amino Acid']
  },
  {
    canonicalSlug: 'biointestil',
    name: 'Biointestil® (Palmarosa Essential Oil & Fiber Complex)',
    canonicalName: 'Biointestil®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'B',
    description: 'Standardized phytobiotic complex combining geraniol from Cymbopogon martinii with prebiotic fiber to modulate dysbiosis and reduce gut bloating.',
    commercialName: 'Biointestil®',
    synonyms: ['Biointestil', 'Biointestil®', 'Geraniol Intestinal Complex'],
    dosage: '300 mg - 600 mg',
    format: 'Microencapsulated Powder',
    purity: 'Patented Complex',
    casNumber: '',
    tags: ['Gut Dysbiosis', 'SIBO Modulation', 'Prebiotic Carrier', 'Phytobiotic']
  },
  {
    canonicalSlug: 'citrimax',
    name: 'Citrimax® (Garcinia cambogia 60% HCA)',
    canonicalName: 'Citrimax®',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Standardized hydroxycitric acid (HCA) extract competitively inhibiting ATP-citrate lyase to attenuate de novo lipogenesis.',
    commercialName: 'Super Citrimax® / Citrimax 60% HCA',
    synonyms: ['Citrimax', 'Citrimax®', 'Super Citrimax', 'Garcinia cambogia extract', 'Hydroxycitric Acid'],
    dosage: '500 mg - 1500 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥60% HCA',
    casNumber: '90045-23-1',
    tags: ['ATP-Citrate Lyase Inhibitor', 'Lipogenesis Attenuation', 'Appetite Modulation']
  },
  {
    canonicalSlug: 'spirulina',
    name: 'Spirulina Organic Powder (Arthrospira platensis)',
    canonicalName: 'Spirulina',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Cyanobacterium superfood rich in phycocyanin, bioavailable iron, chlorophyll, and essential amino acids.',
    commercialName: 'Organic Spirulina Powder 60% Protein',
    synonyms: ['Spirulina', 'Arthrospira platensis', 'Spirulina platensis'],
    dosage: '1000 mg - 3000 mg',
    format: 'Bulk Powder',
    purity: '≥60% Protein',
    casNumber: '724424-92-4',
    tags: ['Phycocyanin', 'Micronutrient Density', 'Heavy Metal Chelation', 'Antioxidant']
  },
  {
    canonicalSlug: 'ubiqsome',
    name: 'Ubiqsome® (Phytosomal Bioavailable CoQ10)',
    canonicalName: 'Ubiqsome®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'B',
    description: 'Phytosome formulation of Coenzyme Q10 delivering 9x greater water dispersibility and superior intracellular uptake.',
    commercialName: 'Ubiqsome®',
    synonyms: ['Ubiqsome', 'Ubiqsome®', 'Phytosomal CoQ10'],
    dosage: '50 mg - 150 mg',
    format: 'Phytosomal Powder',
    purity: 'Phytosomal Complex',
    casNumber: '',
    tags: ['Phytosome Delivery', 'Enhanced CoQ10 Uptake', 'Cellular Energy']
  },
  {
    canonicalSlug: 'papain',
    name: 'Papain (Carica papaya 6000 USP-U/mg)',
    canonicalName: 'Papain',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Broad-spectrum plant endopeptidase assisting protein cleavage into assimilable oligopeptides and reducing post-prandial digestive burden.',
    commercialName: 'Papain Pure / High Activity USP',
    synonyms: ['Papain', 'Carica papaya enzyme', 'Papaine'],
    dosage: '100 mg - 300 mg',
    format: 'Bulk Powder',
    purity: 'High Enzyme Activity',
    casNumber: '9001-73-4',
    tags: ['Proteolytic Cleavage', 'Digestive Comfort', 'Enzymatic Support']
  },
  {
    canonicalSlug: 'gutcare',
    name: 'Gutcare® (Probiotic & Postbiotic Barrier Formula)',
    canonicalName: 'Gutcare®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'B',
    description: 'Proprietary postbiotic and botanical blend formulated to re-establish mucosal sIgA defenses and reinforce intestinal junction integrity.',
    commercialName: 'Gutcare®',
    synonyms: ['Gutcare', 'Gutcare®'],
    dosage: '300 mg - 500 mg',
    format: 'Bulk Powder',
    purity: 'Patented Complex',
    casNumber: '',
    tags: ['Mucosal Barrier', 'Postbiotic Peptides', 'sIgA Defense', 'Gut Health']
  },
  {
    canonicalSlug: 'bitter-melon-extract',
    name: 'Bitter Melon Dry Extract (Momordica charantia 10% Charantin)',
    canonicalName: 'Bitter Melon Dry Extract (Momordica charantia)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Standardized Momordica charantia extract containing charantin and polypeptide-p, stimulating GLUT4 translocation and AMPK activation.',
    commercialName: 'Momordica charantia Extract 10% Charantin',
    synonyms: ['Bitter Melon', 'Momordica charantia', 'Bitter Melon Extract'],
    dosage: '300 mg - 600 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥10% Charantin',
    casNumber: '93333-80-3',
    tags: ['GLUT4 Translocation', 'AMPK Activation', 'Glycemic Control', 'Charantin']
  },
  {
    canonicalSlug: 'gotu-kola-extract',
    name: 'Gotu Kola Dry Extract (Centella asiatica 20% Asiaticosides)',
    canonicalName: 'Gotu Kola Dry Extract (Centella asiatica)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'B',
    description: 'Standardized triterpenoid extract stimulating Type I collagen synthesis, venous microcirculation, and neuroprotective brain-derived neurotrophic factor (BDNF).',
    commercialName: 'Centella asiatica Extract 20% Triterpenes',
    synonyms: ['Gotu Kola', 'Centella asiatica', 'Gotu Kola Extract', 'Asiaticoside'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥20% Asiaticosides',
    casNumber: '84696-21-9',
    tags: ['Microvascular Circulation', 'Collagen I Synthesis', 'Neuroprotection', 'Triterpenes']
  },
  {
    canonicalSlug: 'miodesin',
    name: 'Miodesin™ (Anti-Inflammatory Phytocomplex)',
    canonicalName: 'Miodesin™',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'B',
    description: 'Patented botanical phytocomplex with verified inhibitory action on pro-inflammatory cytokines (IL-1β, IL-6, TNF-α) and COX-2 / NF-κB pathways.',
    commercialName: 'Miodesin™',
    synonyms: ['Miodesin', 'Miodesin™', 'Miodesin Phytocomplex'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: 'Patented Complex',
    casNumber: '',
    tags: ['NF-kB Inhibition', 'COX-2 Downregulation', 'Cytokine Clearance', 'Phytocomplex']
  },
  {
    canonicalSlug: 'silibin',
    name: 'Silibin® (Purified Silybin Phospholipid Complex)',
    canonicalName: 'Silibin®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'B',
    description: 'Purified major active flavanolignan silybin, with high hepatoprotective, free-radical trapping, and Phase I/II balancing properties.',
    commercialName: 'Silibin® / Silybin Pure API',
    synonyms: ['Silibin', 'Silibin®', 'Silybin', 'Silibinin'],
    dosage: '120 mg - 240 mg',
    format: 'Bulk Powder',
    purity: '≥98% Silybin',
    casNumber: '22888-70-6',
    tags: ['Hepatoprotection', 'Phytosomal Silybin', 'Phase I/II Balance', 'Antioxidant']
  },

  // ── PRIORITY C ─────────────────────────────────────────────────────────────
  {
    canonicalSlug: 'imuno-tf',
    name: 'Imuno TF® (Purified Transfer Factors)',
    canonicalName: 'Imuno TF®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'C',
    description: 'Specific low-molecular-weight transfer factors that educate and balance the cell-mediated adaptive immune system.',
    commercialName: 'Imuno TF®',
    synonyms: ['Imuno TF', 'Imuno TF®', 'Transfer Factors'],
    dosage: '50 mg - 100 mg',
    format: 'Bulk Powder',
    purity: 'Pure Transfer Factors',
    casNumber: '',
    tags: ['Transfer Factors', 'Cell-Mediated Immunity', 'Immunomodulation']
  },
  {
    canonicalSlug: 'lactobacillus-acidophilus',
    name: 'Lactobacillus acidophilus (Probiotic Strain)',
    canonicalName: 'Lactobacillus acidophilus',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Classic probiotic producing lactic acid and hydrogen peroxide, suppressing candida and intestinal pathogens.',
    commercialName: 'Lactobacillus acidophilus 100B CFU/g',
    synonyms: ['L. acidophilus', 'Lactobacillus acidophilus'],
    dosage: '1 - 10 Billion CFU',
    format: 'Lyophilized Probiotic Powder',
    purity: '100 Billion CFU/g',
    casNumber: '',
    tags: ['Probiotic Strain', 'Lactic Acid', 'Microbiome Balance']
  },
  {
    canonicalSlug: 'allyl-abg',
    name: 'Allyl ABG™ (Aged Black Garlic Standardized in SAC)',
    canonicalName: 'Allyl ABG™ (Allium sativum)',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'C',
    description: 'Aged black garlic extract standardized in S-allyl-cysteine (SAC), providing potent vascular antioxidant and cardiovascular protection.',
    commercialName: 'Allyl ABG™ (ABG10+®)',
    synonyms: ['Allyl ABG', 'Allyl ABG™', 'Aged Black Garlic', 'Allium sativum'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: 'Standardized S-Allyl-Cysteine',
    casNumber: '',
    tags: ['S-Allyl-Cysteine', 'Cardiovascular Support', 'Aged Black Garlic', 'Antioxidant']
  },
  {
    canonicalSlug: 'beta-carotene',
    name: 'Beta-Carotene 10% / 20% Pure (Provitamin A)',
    canonicalName: 'Beta-Carotene',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Natural carotenoid provitamin converted on-demand to retinol via BCO1 enzyme, providing singlet oxygen quenching.',
    commercialName: 'Natural Beta-Carotene 10% CWS / 20% API',
    synonyms: ['Beta-Carotene', 'Provitamin A', 'Beta Carotene'],
    dosage: '6 mg - 15 mg (10,000 IU)',
    format: 'Bulk Powder (Microencapsulated CWS)',
    purity: '≥10% Beta-Carotene',
    casNumber: '7235-40-7',
    tags: ['Provitamin A', 'Singlet Oxygen Quencher', 'Carotenoid', 'Antioxidant']
  },
  {
    canonicalSlug: 'green-tea-extract',
    name: 'Green Tea Dry Extract (GreenSelect™ / EGCG 50%)',
    canonicalName: 'Green Tea Dry Extract (Camellia sinensis)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Standardized Camellia sinensis extract with high epigallocatechin gallate (EGCG), promoting fat oxidation and COMT-mediated catecholamine sustainment.',
    commercialName: 'GreenSelect™ / Green Tea Extract 50% EGCG',
    synonyms: ['Green Tea Extract', 'GreenSelect', 'GreenSelect™', 'Camellia sinensis', 'EGCG'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥50% EGCG',
    casNumber: '84650-60-2',
    tags: ['EGCG', 'Thermogenesis', 'Fat Oxidation', 'Catechins']
  },
  {
    canonicalSlug: 'l-isoleucine',
    name: 'L-Isoleucine Pure API',
    canonicalName: 'Isoleucine (L-Isoleucine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Branched-chain essential amino acid (BCAA) promoting muscular glucose uptake through independent insulin pathways.',
    commercialName: 'L-Isoleucine USP',
    synonyms: ['Isoleucine', 'L-Isoleucine', 'BCAA'],
    dosage: '1000 mg - 3000 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '73-32-5',
    tags: ['BCAA', 'Muscle Glucose Uptake', 'Protein Anabolism']
  },
  {
    canonicalSlug: 'lycopene',
    name: 'Lycopene 10% (Tomato Extract API)',
    canonicalName: 'Lycopene',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Acyclic carotenoid with exceptionally high quenching rate for singlet molecular oxygen, offering prostate and endothelial protection.',
    commercialName: 'Natural Lycopene 10% / 20% Powder',
    synonyms: ['Lycopene', 'Tomato Lycopene Extract'],
    dosage: '10 mg - 20 mg',
    format: 'Bulk Powder',
    purity: '≥10% Lycopene',
    casNumber: '502-65-8',
    tags: ['Prostate Health', 'Singlet Oxygen Quencher', 'Carotenoid', 'Cardiovascular']
  },
  {
    canonicalSlug: 'chlorella',
    name: 'Chlorella Pyrenoidosa Organic Powder',
    canonicalName: 'Chlorella (Chlorella pyrenoidosa)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Broken-cell-wall green microalgae with high chlorophyll content, binding heavy metals and promoting gastrointestinal transit.',
    commercialName: 'Organic Broken Cell Wall Chlorella',
    synonyms: ['Chlorella', 'Chlorella pyrenoidosa', 'Broken Cell Chlorella'],
    dosage: '1000 mg - 3000 mg',
    format: 'Bulk Powder',
    purity: 'Organic Microalgae',
    casNumber: '',
    tags: ['Heavy Metal Chelation', 'Chlorophyll', 'Detoxification', 'Gut Transit']
  },
  {
    canonicalSlug: 'fitnox',
    name: 'FitNox® (Plant-Based Nitric Oxide Booster)',
    canonicalName: 'FitNox®',
    category: 'raw_material',
    type: 'raw_material',
    priority: 'C',
    description: 'Clinically studied plant-based matrix (Moringa, Pomegranate, Kaempferia) boosting endogenous nitrate-to-nitrite conversion and endothelial NO levels.',
    commercialName: 'FitNox®',
    synonyms: ['FitNox', 'FitNox®', 'Nitric Oxide Plant Complex'],
    dosage: '250 mg',
    format: 'Standardized Powder',
    purity: 'Standardized Complex',
    casNumber: '',
    tags: ['Nitric Oxide Matrix', 'Endothelial Function', 'Vasodilation', 'Performance']
  },
  {
    canonicalSlug: 'l-leucine',
    name: 'L-Leucine Pure API',
    canonicalName: 'Leucine (L-Leucine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Primary branched-chain amino acid directly triggering the mTORC1 pathway for muscle protein synthesis and sarcopenia prevention.',
    commercialName: 'L-Leucine Pure USP',
    synonyms: ['Leucine', 'L-Leucine', 'BCAA Leucine'],
    dosage: '2000 mg - 5000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '61-90-5',
    tags: ['mTORC1 Trigger', 'Muscle Protein Synthesis', 'BCAA', 'Anabolism']
  },
  {
    canonicalSlug: 'betaine-tmg',
    name: 'Betaine Anhydrous (Trimethylglycine / TMG)',
    canonicalName: 'Betaine (Trimethylglycine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Zwitterionic methyl donor transferring methyl groups via BHMT enzyme to convert homocysteine to methionine, supporting hepatic methylation.',
    commercialName: 'Betaine Anhydrous (TMG) Pure USP',
    synonyms: ['Betaine', 'TMG', 'Trimethylglycine', 'Betaine Anhydrous'],
    dosage: '500 mg - 1500 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '107-43-7',
    tags: ['BHMT Methyl Donor', 'Homocysteine Remethylation', 'Osmoprotection', 'Liver Support']
  },
  {
    canonicalSlug: 'ginger-extract',
    name: 'Ginger Root Dry Extract (Zingiber officinale 5% Gingerols)',
    canonicalName: 'Ginger',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Standardized ginger extract rich in gingerols and shogaols, stimulating gastric motility, bile production, and inhibiting 5-HT3 receptors.',
    commercialName: 'Ginger Dry Extract 5% Gingerols',
    synonyms: ['Ginger', 'Ginger Extract', 'Zingiber officinale', 'Ginger Root'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥5% Gingerols',
    casNumber: '84696-15-1',
    tags: ['Gastric Motility', 'Prokinetic', 'Anti-Nausea', 'Gingerols']
  },
  {
    canonicalSlug: 'gum-arabic',
    name: 'Gum Arabic (Acacia senegal Prebiotic Fiber)',
    canonicalName: 'Gum Arabic (Gum Acacia)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'High-molecular-weight soluble prebiotic polysaccharide slowly fermented by Bifidobacteria into short-chain fatty acids (SCFAs).',
    commercialName: 'Gum Acacia / Arabic Powder Pharma Grade',
    synonyms: ['Gum Arabic', 'Gum Acacia', 'Acacia Fiber', 'Acacia senegal'],
    dosage: '5 g - 10 g',
    format: 'Bulk Powder',
    purity: 'Pharma / Food Grade',
    casNumber: '9000-01-5',
    tags: ['Prebiotic Fiber', 'SCFA Production', 'Bifidogenic', 'Intestinal Comfort']
  },
  {
    canonicalSlug: 'grapefruit-extract',
    name: 'Grapefruit Dry Extract (Citrus paradisi 5% Flavones)',
    canonicalName: 'Grapefruit Dry Extract (Citrus paradisi), standardized to 5% flavones',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Standardized Citrus paradisi extract providing naringin and bioflavonoids that modulate microvascular permeability.',
    commercialName: 'Citrus paradisi Extract 5% Bioflavonoids',
    synonyms: ['Grapefruit Extract', 'Citrus paradisi extract', 'Naringin Extract'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥5% Flavones',
    casNumber: '90045-43-5',
    tags: ['Flavones', 'Bioflavonoids', 'Microcirculation', 'Antioxidant']
  },
  {
    canonicalSlug: 'alpha-lipoic-acid',
    name: 'Alpha-Lipoic Acid (ALA Pure API)',
    canonicalName: 'Alpha-Lipoic Acid (ALA)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Universal amphiphilic antioxidant regenerating Vitamins C and E, elevating intracellular glutathione, and enhancing insulin-mediated glucose transport.',
    commercialName: 'Alpha-Lipoic Acid (Thioctic Acid) Pure USP',
    synonyms: ['Alpha-Lipoic Acid', 'ALA', 'Thioctic Acid', 'R-ALA'],
    dosage: '300 mg - 600 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '1077-28-7',
    tags: ['Universal Antioxidant', 'Insulin Sensitivity', 'Glutathione Regeneration', 'Mitochondria']
  },
  {
    canonicalSlug: 'inulin',
    name: 'Inulin Prebiotic FOS (Chicory Root Extract)',
    canonicalName: 'Inulin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Fructooligosaccharide (FOS) prebiotic fiber selectively stimulating Bifidobacterium proliferation and enhancing colonic calcium absorption.',
    commercialName: 'Inulin Chicory Root Powder 90%',
    synonyms: ['Inulin', 'Chicory Inulin', 'FOS', 'Prebiotic Inulin'],
    dosage: '3 g - 5 g',
    format: 'Bulk Soluble Powder',
    purity: '≥90% Fructans',
    casNumber: '9005-80-5',
    tags: ['FOS Prebiotic', 'Bifidogenic', 'Short Chain Fatty Acids', 'Colonic Health']
  },
  {
    canonicalSlug: 'myo-inositol',
    name: 'Myo-Inositol Pure API',
    canonicalName: 'Inositol',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Second messenger precursor for insulin signaling and gonadotropin receptors, restoring ovulatory function and metabolic insulin sensitivity.',
    commercialName: 'Myo-Inositol Pure USP / Food Grade',
    synonyms: ['Inositol', 'Myo-Inositol', 'Vitamin B8'],
    dosage: '2000 mg - 4000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '87-89-8',
    tags: ['Insulin Second Messenger', 'Ovarian Function', 'Metabolic Balance', 'Inositol']
  },
  {
    canonicalSlug: 'chrysin',
    name: 'Chrysin 99% (Passiflora caerulea Extract)',
    canonicalName: 'Chrysin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Naturally occurring flavone with aromatase inhibitory, PPAR-gamma activating, and antioxidant characteristics.',
    commercialName: 'Chrysin 99% Pure API',
    synonyms: ['Chrysin', '5,7-Dihydroxyflavone', 'Flavone Chrysin'],
    dosage: '250 mg - 500 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '480-40-0',
    tags: ['Aromatase Inhibitor', 'Flavone', 'PPAR-gamma', 'Antioxidant']
  },
  {
    canonicalSlug: 'glycine',
    name: 'Glycine Pure API (Aminoacetic Acid)',
    canonicalName: 'Glycine',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Simplest non-essential amino acid required for collagen triple helix formation, glutathione synthesis, and inhibitory neurotransmission in the CNS.',
    commercialName: 'Glycine Pure USP / Ph. Eur.',
    synonyms: ['Glycine', 'Aminoacetic Acid', 'L-Glycine'],
    dosage: '2000 mg - 5000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99.5%',
    casNumber: '56-40-6',
    tags: ['Collagen Building Block', 'Glutathione Synthesis', 'Inhibitory Neurotransmitter', 'Sleep']
  },
  {
    canonicalSlug: 'astaxanthin',
    name: 'Astaxanthin (Haematococcus pluvialis Extract)',
    canonicalName: 'Astaxanthin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Potent keto-carotenoid providing membrane-spanning antioxidant protection across mitochondrial and cellular bilayers.',
    commercialName: 'Astaxanthin Oleoresin 5% / 10% / Pure Powder',
    synonyms: ['Astaxanthin', 'Natural Astaxanthin', 'Haematococcus pluvialis'],
    dosage: '4 mg - 12 mg',
    format: 'Bulk Powder / Oleoresin',
    purity: '≥10% Astaxanthin',
    casNumber: '472-61-7',
    tags: ['Mitochondrial Membrane Protection', 'Carotenoid', 'Antioxidant']
  },
  {
    canonicalSlug: 'sam-e',
    name: 'S-Adenosyl-L-Methionine (SAM-e Disulfate Tosylate)',
    canonicalName: 'S-Adenosyl-L-Methionine (SAM-e)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Universal physiological methyl donor donating methyl groups to DNA, proteins, phospholipids, and neurotransmitters in the transmethylation pathway.',
    commercialName: 'SAMe Disulfate Tosylate API',
    synonyms: ['SAM-e', 'SAMe', 'S-Adenosylmethionine', 'Ademetionine'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Powder (Disulfate Tosylate)',
    purity: '≥98%',
    casNumber: '97540-22-2',
    tags: ['Universal Methyl Donor', 'Transmethylation', 'Neurotransmitter Synthesis', 'Liver Support']
  },
  {
    canonicalSlug: 'zeaxanthin',
    name: 'Zeaxanthin 5% / 10% (Marigold Extract)',
    canonicalName: 'Zeaxanthin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Selective macular xanthophyll carotenoid concentrating in the fovea centralis to filter high-energy blue light and neutralize photochemical free radicals.',
    commercialName: 'Natural Zeaxanthin 5% / 10% CWS Powder',
    synonyms: ['Zeaxanthin', 'Tagetes erecta extract'],
    dosage: '2 mg - 5 mg',
    format: 'Bulk Powder',
    purity: '≥5% Zeaxanthin',
    casNumber: '144-68-3',
    tags: ['Macular Pigment', 'Blue Light Filter', 'Xanthophyll', 'Visual Acuity']
  },
  {
    canonicalSlug: 'activated-charcoal',
    name: 'Activated Charcoal (Medicinal Carbon USP)',
    canonicalName: 'Activated Charcoal',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'High surface area porous carbon matrix adsorbing intestinal toxins, heavy metals, and gases to reduce systemic endotoxemia.',
    commercialName: 'Activated Charcoal Powder USP',
    synonyms: ['Activated Charcoal', 'Medicinal Carbon', 'Activated Carbon'],
    dosage: '500 mg - 1000 mg',
    format: 'Fine Black Powder',
    purity: 'Pharma Grade USP',
    casNumber: '7440-44-0',
    tags: ['Adsorption', 'Toxin Binding', 'Gastrointestinal Cleansing', 'Gas Relief']
  },
  {
    canonicalSlug: 'lutein',
    name: 'Lutein 10% / 20% (Tagetes erecta Extract)',
    canonicalName: 'Lutein',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Dietary xanthophyll carotenoid forming the macular optical density shield in the retina, protecting against photo-oxidative stress.',
    commercialName: 'Natural Lutein 10% CWS / 20% Powder',
    synonyms: ['Lutein', 'Tagetes erecta extract', 'Marigold Lutein'],
    dosage: '10 mg - 20 mg',
    format: 'Bulk Powder',
    purity: '≥10% Lutein',
    casNumber: '127-40-2',
    tags: ['Macular Density', 'Retinal Photoprotection', 'Xanthophyll', 'Eye Health']
  },
  {
    canonicalSlug: 'psyllium-husk',
    name: 'Psyllium Husk Powder (Plantago ovata)',
    canonicalName: 'Psyllium (Plantago psyllium / Plantago ovata)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Soluble, mucilaginous bulk-forming prebiotic fiber that regulates bowel regularity, traps bile acids, and slows postprandial glucose absorption.',
    commercialName: 'Psyllium Husk Powder 95% / 99% Purity',
    synonyms: ['Psyllium', 'Psyllium Husk', 'Plantago ovata', 'Plantago psyllium', 'Ispaghula'],
    dosage: '5 g - 10 g',
    format: 'Bulk Powder (95% Purity)',
    purity: '≥95% Husk',
    casNumber: '',
    tags: ['Mucilaginous Fiber', 'Bile Acid Trapping', 'Bowel Transit', 'Glucose Blunting']
  },
  {
    canonicalSlug: 'indole-3-carbinol',
    name: 'Indole-3-Carbinol (I3C Pure API)',
    canonicalName: 'Indole-3-Carbinol (I3C)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Glucosinolate breakdown product promoting CYP1A1-mediated 2-hydroxyestrone pathway over the 16-alpha-hydroxyestrone metabolite.',
    commercialName: 'Indole-3-Carbinol (I3C) 99% API',
    synonyms: ['Indole-3-Carbinol', 'I3C', 'Indole 3 Carbinol'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '700-06-1',
    tags: ['Estrogen Metabolism', '2-OHE Pathway', 'Cruciferous Compound', 'Cellular Balance']
  },
  {
    canonicalSlug: 'silymarin',
    name: 'Silymarin 80% (Silybum marianum Extract)',
    canonicalName: 'Silymarin',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Flavonolignan complex extracted from milk thistle providing hepatocyte membrane stabilization and antioxidant protection.',
    commercialName: 'Silymarin 80% Milk Thistle API',
    synonyms: ['Silymarin', 'Milk Thistle Extract', 'Silimarin', 'Silybum marianum'],
    dosage: '200 mg - 400 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥80% Silymarin',
    casNumber: '65666-07-1',
    tags: ['Hepatocyte Membrane Protection', 'Milk Thistle', 'Flavonolignans', 'Antioxidant']
  },
  {
    canonicalSlug: 'bilberry-extract',
    name: 'Bilberry Dry Extract (Vaccinium myrtillus 25% Anthocyanidins)',
    canonicalName: 'Bilberry Dry Extract (Vaccinium myrtillus), 25% anthocyanidins',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Standardized Vaccinium myrtillus extract rich in anthocyanins, supporting microvascular capillary resistance and retinal purple rhodopsin regeneration.',
    commercialName: 'Bilberry Extract 25% Anthocyanosides',
    synonyms: ['Bilberry Extract', 'Vaccinium myrtillus', 'Bilberry Dry Extract', 'Anthocyanidins'],
    dosage: '100 mg - 200 mg',
    format: 'Bulk Standardized Powder',
    purity: '≥25% Anthocyanins',
    casNumber: '84082-34-8',
    tags: ['Microvascular Resistance', 'Rhodopsin Support', 'Anthocyanidins', 'Vision']
  },
  {
    canonicalSlug: 'l-cysteine',
    name: 'L-Cysteine Hydrochloride Monohydrate API',
    canonicalName: 'Cysteine (L-Cysteine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Semi-essential sulfur amino acid acting as the rate-limiting substrate for intracellular glutathione synthesis and keratin disulfide bonding.',
    commercialName: 'L-Cysteine HCl Monohydrate USP',
    synonyms: ['Cysteine', 'L-Cysteine', 'L-Cysteine HCl'],
    dosage: '500 mg - 1000 mg',
    format: 'Bulk Crystalline Powder',
    purity: '≥99%',
    casNumber: '7048-04-6',
    tags: ['Sulfur Amino Acid', 'Glutathione Rate-Limiter', 'Disulfide Bridges']
  },
  {
    canonicalSlug: 'l-valine',
    name: 'L-Valine Pure API',
    canonicalName: 'Valine (L-Valine)',
    category: 'supplement',
    type: 'raw_material',
    priority: 'C',
    description: 'Branched-chain essential amino acid (BCAA) essential for glycogen resynthesis in muscle tissue and preventing central nervous fatigue.',
    commercialName: 'L-Valine Pure USP',
    synonyms: ['Valine', 'L-Valine', 'BCAA Valine'],
    dosage: '1000 mg - 3000 mg',
    format: 'Bulk Powder',
    purity: '≥99%',
    casNumber: '72-18-4',
    tags: ['BCAA', 'Glycogen Resynthesis', 'Muscle Energy', 'Essential Amino Acid']
  }
];

async function run() {
  console.log(`Starting Fagron NutriGen Seeding & Multi-Program Association (${NUTRIGEN_PRODUCTS.length} products)...`);

  let createdCount = 0;
  let updatedCount = 0;

  for (const item of NUTRIGEN_PRODUCTS) {
    const docRef = adminDb.collection('products').doc(item.canonicalSlug);
    const docSnap = await docRef.get();

    const programAssociation = {
      id: NUTRIGEN_PROGRAM_ID,
      slug: NUTRIGEN_SLUG,
      name: NUTRIGEN_PROGRAM_NAME,
      priority: item.priority,
      metadata: {
        commercialName: item.commercialName,
        purity: item.purity,
        format: item.format,
        dosage: item.dosage,
        casNumber: item.casNumber || ''
      },
      updatedAt: new Date()
    };

    const searchAliases = [
      NUTRIGEN_PROGRAM_NAME,
      'NutriGen',
      'Fagron Genomics',
      'Fagron Iberia',
      item.canonicalName,
      ...(item.synonyms || [])
    ];

    if (docSnap.exists) {
      const existing = docSnap.data();
      const existingPrograms = Array.isArray(existing.programs) ? existing.programs : [];
      const existingTags = Array.isArray(existing.tags) ? existing.tags : [];
      const existingSupplierIds = Array.isArray(existing.supplierIds) ? existing.supplierIds : [];

      // Preserve any other programs (like TeloTest, TrichoTest with their own Priorities) and update/add NutriGen
      const filteredPrograms = existingPrograms.filter(p => p.id !== NUTRIGEN_PROGRAM_ID && p.slug !== NUTRIGEN_SLUG);
      filteredPrograms.push(programAssociation);

      // Merge tags
      const updatedTags = Array.from(new Set([
        ...existingTags,
        NUTRIGEN_SLUG,
        NUTRIGEN_PROGRAM_NAME,
        'NutriGen',
        'Fagron Genomics',
        'Nutritional Genomics',
        'Metabolic Health',
        ...(item.tags || [])
      ]));

      // Merge supplierIds
      const updatedSupplierIds = Array.from(new Set([
        ...existingSupplierIds,
        FAGRON_IBERIA_SUPPLIER_ID
      ]));

      // Merge searchAliases
      const existingAliases = Array.isArray(existing.searchAliases) ? existing.searchAliases : [];
      const updatedAliases = Array.from(new Set([...existingAliases, ...searchAliases]));

      await docRef.update({
        programs: filteredPrograms,
        tags: updatedTags,
        supplierIds: updatedSupplierIds,
        searchAliases: updatedAliases,
        supplier: existing.supplier || FAGRON_IBERIA_SUPPLIER_NAME,
        updatedAt: new Date()
      });

      console.log(`[UPDATED] ${item.canonicalSlug} -> NutriGen Priority ${item.priority} (Total Programs: ${filteredPrograms.length})`);
      updatedCount++;
    } else {
      // Create new canonical product
      const newDoc = {
        name: item.name,
        canonicalName: item.canonicalName,
        category: item.category,
        type: item.type,
        status: 'active',
        isActive: true,
        description: item.description,
        shortDesc: item.description,
        supplier: FAGRON_IBERIA_SUPPLIER_NAME,
        supplierIds: [FAGRON_IBERIA_SUPPLIER_ID],
        tags: [
          NUTRIGEN_SLUG,
          NUTRIGEN_PROGRAM_NAME,
          'NutriGen',
          'Fagron Genomics',
          'Nutritional Genomics',
          'Metabolic Health',
          ...(item.tags || [])
        ],
        searchAliases: searchAliases,
        programs: [programAssociation],
        dosage: item.dosage,
        format: item.format,
        purity: item.purity,
        casNumber: item.casNumber || '',
        variants: [
          {
            id: `v_fagron_${item.canonicalSlug}`,
            sku: `FAGRON-${item.canonicalSlug.toUpperCase()}`,
            supplier: FAGRON_IBERIA_SUPPLIER_NAME,
            supplierId: FAGRON_IBERIA_SUPPLIER_ID,
            presentation: item.format || 'Bulk API Powder',
            dosage: item.dosage || 'Standard',
            format: item.format || 'Bulk Powder',
            type: 'raw_material',
            productType: 'api_raw_material',
            price: 48,
            unit_price: 48,
            supplierCost: 26,
            stock: 100,
            status: 'active'
          }
        ],
        createdAt: new Date(),
        updatedAt: new Date()
      };

      await docRef.set(newDoc);
      console.log(`[CREATED] ${item.canonicalSlug} (${item.name}) -> NutriGen Priority ${item.priority}`);
      createdCount++;
    }
  }

  console.log(`\nNutriGen Seeding Finished Successfully! Created: ${createdCount}, Updated: ${updatedCount}, Total: ${NUTRIGEN_PRODUCTS.length}`);
  process.exit(0);
}

run().catch(err => {
  console.error('Error seeding NutriGen products:', err);
  process.exit(1);
});
