'use client';

import React from 'react';
import { History, CheckCircle2, Clock, Send, FileText, ArrowRight } from 'lucide-react';
import StatusBadge from '../../ui/StatusBadge';

export default function HistoryTab({ quotation, quotationId }) {
  if (!quotation) return null;

  const events = [
    {
      title: 'Quotation Created',
      desc: `Generated by ${quotation.accountManagerId || quotation.doctorName || 'System Commercial Engine'}`,
      date: quotation.createdAt
        ? new Date(quotation.createdAt?.toDate ? quotation.createdAt.toDate() : quotation.createdAt).toLocaleString()
        : 'Initial Creation',
      icon: FileText,
      color: 'var(--color-primary, #003666)',
      bg: 'var(--color-primary-light, #eff6ff)'
    },
    ...(quotation.url ? [{
      title: 'Official Document Rendered',
      desc: 'PDF generated with high-resolution vector layout',
      date: 'Completed',
      icon: CheckCircle2,
      color: '#15803d',
      bg: '#f0fdf4'
    }] : []),
    {
      title: `Current Lifecycle Status: ${String(quotation.status || 'draft').toUpperCase()}`,
      desc: 'Tracked in Firestore authoritative state machine',
      date: 'Active',
      icon: Clock,
      color: '#d97706',
      bg: '#fffbeb'
    }
  ];

  return (
    <div style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: 10, padding: '16px' }}>
        <div style={{ fontSize: '0.82rem', fontWeight: 700, color: '#0f172a', marginBottom: 14, display: 'flex', alignItems: 'center', gap: 6 }}>
          <History size={16} color="var(--color-primary, #003666)" />
          <span>Audit Trail & Lifecycle Events</span>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {events.map((ev, idx) => {
            const IconComp = ev.icon;
            return (
              <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                <div style={{ width: 32, height: 32, borderRadius: 8, background: ev.bg, color: ev.color, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <IconComp size={16} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: '0.84rem', fontWeight: 600, color: '#0f172a' }}>{ev.title}</div>
                  <div style={{ fontSize: '0.74rem', color: '#64748b', marginTop: 1 }}>{ev.desc}</div>
                </div>
                <div style={{ fontSize: '0.72rem', color: '#94a3b8' }}>
                  {ev.date}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
