"use client";

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../../context/AuthContext';
import toast from 'react-hot-toast';
import { logger } from '../../../utils/logger';
import { GOALS } from '../../../constants/catalogFilters';
import { catalogRepository } from '../../../repositories/catalogRepository';
import { productRepository } from '../../../repositories/productRepository';


import { emptyCatalog, CATALOG_STATUS } from '../../../schemas/catalogSchema';
import { useCatalogData } from '../../admin/catalog/useCatalogData';
import SmartCatalogWelcomeModal from '../../admin/catalog/modals/SmartCatalogWelcomeModal';
import CatalogAIAssistantPanel from '../../admin/catalog/views/CatalogAIAssistantPanel';
import CatalogPreviewAndShareModal from './CatalogPreviewAndShareModal';
import CenterPanel from './CenterPanel';

import CatalogTableView from '../../admin/catalog/views/CatalogTableView';
import { AtlasCatalogAgent } from '../../../services/AtlasCatalogAgent';
import {
  generateCatalogPdf,
  downloadPdfBlob,
  generateCatalogExcel,
  downloadExcelBlob,
} from '../../../services/catalogPdfEngine/index.js';
import { useCatalogBuilderStore } from '../../../stores/useCatalogBuilderStore';

import { ArrowLeft, Search, Plus, Check, Trash2, SlidersHorizontal, BarChart2, ShieldCheck, Activity, Brain, Target, Shield, Box, X, Layers, LayoutTemplate, Calendar, Percent, Sparkles as SparklesIcon, Download, ChevronDown, ChevronUp, BookOpen, Mail, MessageSquare, ExternalLink, Building2, FileText } from '@/lib/icons';

const PRODUCT_TYPES = [
  { id: 'lyophilized_peptide', label: 'Lyophilized Peptides' },
  { id: 'api_peptide', label: 'API Peptides' },
  { id: 'api_supplement', label: 'API Supplements' },
  { id: 'injectable', label: 'Injectables' },
  { id: 'capsule_tablet', label: 'Capsules / Tablets' },
];

// SmartCatalogWelcomeModal imported

export default function CatalogCreatorFlow({ ownerId, ownerType, editingCatalog = null, onBack }) {
  const { userProfile } = useAuth();
  const router = useRouter();
  const pathname = usePathname();
  const tenantId = userProfile?.assignedTenantId || userProfile?.tenantId || ownerId;

  // Modals & States
  const [showWelcomeModal, setShowWelcomeModal] = useState(
    location.state?.selectedProducts?.length > 0
      ? false
      : location.state?.showWelcomeModal !== false
  );
  const [isMobile, setIsMobile] = useState(window.innerWidth < 1024);
  const [mobileStep, setMobileStep] = useState(1);
  const [activeAccordionOpen, setActiveAccordionOpen] = useState(true);
  const [publishedAccordionOpen, setPublishedAccordionOpen] = useState(false);

  // Global Data
  const { variants: allProducts, loading: loadingAll } = useCatalogData();

  // Zustand store integration for persistent catalog draft
  const storeSelectedProducts = useCatalogBuilderStore((state) => state.selectedProducts);
  const storeCartProductsData = useCatalogBuilderStore((state) => state.cartProductsData);
  const storeCatalogMeta = useCatalogBuilderStore((state) => state.catalogMeta);
  const storePublishOptions = useCatalogBuilderStore((state) => state.publishOptions);
  const storeIsDraftActive = useCatalogBuilderStore((state) => state.isDraftActive);

  const startDraft = useCatalogBuilderStore((state) => state.startDraft);
  const updateDraft = useCatalogBuilderStore((state) => state.updateDraft);
  const updateMeta = useCatalogBuilderStore((state) => state.updateMeta);
  const addProducts = useCatalogBuilderStore((state) => state.addProducts);
  const clearDraft = useCatalogBuilderStore((state) => state.clearDraft);

  // Mapped variables
  const catalogCart = storeSelectedProducts;
  const cartProducts = storeCartProductsData;
  const catalogMeta = storeCatalogMeta;
  const publishOptions = storePublishOptions;

  const setCatalogCart = (newIds) => {
    updateDraft({ selectedProducts: newIds });
  };
  const setCartProducts = (newData) => {
    updateDraft({ cartProductsData: newData });
  };
  const setCatalogMeta = (newMetaVal) => {
    if (typeof newMetaVal === 'function') {
      updateMeta(newMetaVal(storeCatalogMeta));
    } else {
      updateMeta(newMetaVal);
    }
  };
  const setPublishOptions = (newOpts) => {
    if (typeof newOpts === 'function') {
      updateDraft({ publishOptions: newOpts(storePublishOptions) });
    } else {
      updateDraft({ publishOptions: newOpts });
    }
  };

  const [loadingCart, setLoadingCart] = useState(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const [generationState, setGenerationState] = useState({ isGenerating: false, step: 0 });
  const GENERATION_STEPS = [
    'Initializing layout...',
    'Applying pricing rules...',
    'Generating PDF & Excel documents...',
    'Finalizing publish...',
  ];

  const [showAIDrawer, setShowAIDrawer] = useState(false);
  const [pastCatalogs, setPastCatalogs] = useState([]);
  const [pricingMultiplier, setPricingMultiplier] = useState({
    basePriceKey: 'cost',
    incrementPercent: 0,
  });

  useEffect(() => {
    if (tenantId) {
      catalogRepository.getCatalogsByOwner(tenantId).then(setPastCatalogs).catch(console.error);
    }
  }, [tenantId]);

  const applyMultiplier = () => {
    const multiplier = 1 + Number(pricingMultiplier.incrementPercent) / 100;
    const updated = cartProducts.map((p) => {
      const base = Number(p[pricingMultiplier.basePriceKey]) || 0;
      return { ...p, msrp: base * multiplier, price: base * multiplier, customPriceApplied: true };
    });
    setCartProducts(updated);
    toast.success(`Multiplier applied! Prices calculated over ${pricingMultiplier.basePriceKey}.`);
  };

  const loadPastCatalog = (pastCatalog) => {
    setCatalogMeta((prev) => ({
      ...prev,
      title: pastCatalog.title + ' (Copy)',
      description: pastCatalog.description,
      territory: pastCatalog.territory || '',
      language: pastCatalog.language || 'English',
      goals: pastCatalog.goals || [],
      categories: pastCatalog.categories || [],
      date: new Date().toISOString().split('T')[0],
      targetAudience: pastCatalog.targetAudience || 'patients',
    }));
    setCatalogCart(pastCatalog.selectedProducts || []);
    if (pastCatalog.cartProductsSnapshot) {
      setCartProducts(pastCatalog.cartProductsSnapshot);
    }
    toast.success('Past catalog loaded successfully. You can now edit and publish as new.');
  };

  // Filtered Mode architecture
  const isFilteredMode = location.state?.type === 'filtered' && !!location.state?.sourceFilters;
  const hookOptions = useMemo(() => {
    if (isFilteredMode) {
      return { ...location.state.sourceFilters, pageSize: 1000, skipFetch: false };
    }
    return { pageSize: 1, skipFetch: true };
  }, [isFilteredMode, location.state]);

  const { variants: filteredVariants, loading: loadingFiltered } = useCatalogData(hookOptions);
  const [hasInitializedFilter, setHasInitializedFilter] = useState(false);

  useEffect(() => {
    if (isFilteredMode && !loadingFiltered && !hasInitializedFilter) {
      const ids = filteredVariants.map((v) => v.id);
      setCatalogCart(ids);
      setCartProducts(filteredVariants);
      setHasInitializedFilter(true);
      if (showWelcomeModal) setShowWelcomeModal(false);
    }
  }, [isFilteredMode, loadingFiltered, hasInitializedFilter, filteredVariants, showWelcomeModal]);

  // Table state
  const [matrixViewType, setMatrixViewType] = useState('grouped');
  const [page, setPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(20);

  const [showPublishOptions, setShowPublishOptions] = useState(false);

  // Preview & Share states
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [previewBlobUrl, setPreviewBlobUrl] = useState(null);
  const [generatingPreview, setGeneratingPreview] = useState(false);
  const [activeShareTab, setActiveShareTab] = useState('email');

  // Share form states
  const [shareEmail, setShareEmail] = useState('');
  const [shareEmailSubject, setShareEmailSubject] = useState('');
  const [shareEmailBody, setShareEmailBody] = useState('');
  const [sharePhone, setSharePhone] = useState('');
  const [shareWhatsAppText, setShareWhatsAppText] = useState('');
  const [shareBiginEmail, setShareBiginEmail] = useState('');
  const [shareBiginStage, setShareBiginStage] = useState('qualification');
  const [shareBiginNotes, setShareBiginNotes] = useState('');
  const [biginSyncing, setBiginSyncing] = useState(false);

  const hasInitialized = useRef(false);

  useEffect(() => {
    if (hasInitialized.current) return;

    // Check if we have incoming products from route state (Items tab)
    const incomingProducts = location.state?.catalogCart || location.state?.selectedProducts;
    const incomingProductsData = location.state?.catalogCartData || [];
    const incomingMeta = location.state?.catalogMeta;

    if (incomingProducts && incomingProducts.length > 0) {
      if (storeIsDraftActive) {
        addProducts(incomingProducts, incomingProductsData);
        if (incomingMeta) {
          updateMeta(incomingMeta);
        }
      } else {
        startDraft(incomingProducts, incomingProductsData, incomingMeta);
      }
    } else if (editingCatalog) {
      startDraft(editingCatalog.selectedProducts || [], editingCatalog.cartProductsSnapshot || [], {
        title: editingCatalog.title || '',
        description: editingCatalog.description || '',
        territory: editingCatalog.territory || '',
        language: editingCatalog.language || 'English',
        goals: editingCatalog.goals || [],
        categories: editingCatalog.categories || [],
        date: editingCatalog.date || new Date().toISOString().split('T')[0],
        targetAudience: editingCatalog.targetAudience || 'patients',
      });
    } else if (!storeIsDraftActive) {
      startDraft([], [], null);
    }

    hasInitialized.current = true;
  }, [location.state, editingCatalog, storeIsDraftActive, startDraft, addProducts, updateMeta]);

  // Load Data
  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 1024);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Sync local changes in catalogCart to fetch if needed
  // Note: we mainly rely on catalogCartData from the router now.
  useEffect(() => {
    if (isFilteredMode) return; // Filtered mode handles itself

    const missingIds = catalogCart.filter(
      (id) => !cartProducts.some((p) => p.id === id || p.productId === id)
    );
    if (missingIds.length > 0) {
      setLoadingCart(true);
      const fetchMissing = async () => {
        try {
          const fetchedVariants = await productRepository.fetchProductsWithVariantsByIds(missingIds);

          setCartProducts((prev) => {
            const newCart = [...prev, ...fetchedVariants];
            // Filter by selected parent products or exact variant ID
            return newCart.filter(
              (p) => catalogCart.includes(p.id) || catalogCart.includes(p.productId)
            );
          });
        } catch (e) {
          logger.error('Failed to fetch cart missing products in CatalogCreatorFlow', { error: e.message });
        } finally {
          setLoadingCart(false);
        }
      };
      fetchMissing();
    }
  }, [catalogCart, isFilteredMode]);


  // Auto-generate if products were pre-selected
  useEffect(() => {
    if (
      cartProducts.length > 0 &&
      location.state?.selectedProducts?.length > 0 &&
      !autoGenerated &&
      !location.state?.catalogMeta
    ) {
      handleGenerateSmartCatalog(location.state.selectedProducts);
      setAutoGenerated(true);
    }
  }, [cartProducts, autoGenerated, location.state]);

  // Handle Initial Welcome Selection
  const handleWelcomeSelection = async (type) => {
    setShowWelcomeModal(false);

    if (type === 'selected' || type === 'smart') {
      const initialIds = location.state?.selectedProducts || [];
      setCatalogCart(initialIds);
      if (type === 'smart') {
        handleGenerateSmartCatalog(initialIds);
      }
    }
  };

  const handleGenerateSmartCatalog = async (ids) => {
    if (!ids || ids.length === 0) {
      toast.error('Please select products first to generate a smart catalog.');
      return;
    }
    setIsGeneratingAI(true);
    const toastId = toast.loading('Atlas AI is analyzing your products and generating a draft...');
    try {
      // We use cartProducts to guarantee we have the full product data
      const selectedProductsFull = cartProducts.filter((p) => ids.includes(p.id));
      const aiData = await AtlasCatalogAgent.generateCatalogDraft(selectedProductsFull);

      setCatalogMeta((prev) => ({
        ...prev,
        title: aiData.name || '',
        description: aiData.description || '',
        goals: aiData.clinicalGoals || [],
        categories: aiData.categories || [],
      }));
      toast.success('Atlas AI has drafted your catalog!', { id: toastId });
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate AI catalog.', { id: toastId });
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const { products: tableProducts, variants: tableVariants } = useMemo(() => {
    const parentMap = new Map();
    // Filter the cartProducts to only include what's currently in catalogCart
    const activeCartProducts = cartProducts.filter(
      (p) => catalogCart.includes(p.id) || catalogCart.includes(p.productId)
    );

    activeCartProducts.forEach((v) => {
      const parentId =
        v.parentProductId ||
        v.originalProduct?.id ||
        v.productId ||
        (v.id ? v.id.split('-')[0] : v.name);
      if (!parentMap.has(parentId)) {
        parentMap.set(parentId, {
          id: parentId,
          name:
            v.originalProduct?.name ||
            v.parentProductId ||
            v.productName ||
            v.name ||
            'Unknown Product',
          category: v.originalProduct?.category || v.category || 'Peptide',
          images: v.originalProduct?.images || v.images || [],
          variants: [],
        });
      }
      parentMap.get(parentId).variants.push(v);
    });
    return {
      products: Array.from(parentMap.values()),
      variants: activeCartProducts,
    };
  }, [cartProducts, catalogCart]);

  const uniqueProductsCount = useMemo(() => {
    return tableProducts.length;
  }, [tableProducts]);

  // Cart Metrics
  const cartMetrics = useMemo(() => {
    const itemsInCart = cartProducts;

    let score = 0;
    if (catalogMeta.title) score += 20;
    if (catalogCart.length > 0) score += 40;
    if (catalogCart.length > 5) score += 20;
    if (itemsInCart.some((i) => i.hasCoa)) score += 20;

    let types = {};
    itemsInCart.forEach((i) => {
      types[i.productType] = (types[i.productType] || 0) + 1;
    });

    return {
      count: catalogCart.length,
      completenessScore: score,
      breakdown: types,
    };
  }, [catalogCart, cartProducts, catalogMeta]);

  const handleSelectionChange = (newIds) => {
    // Sync table selection with cart
    setCatalogCart(newIds);
  };

  const saveCatalog = async (shareConfig = null) => {
    if (!catalogMeta.title) {
      toast.error('Catalog must have a title');
      return;
    }
    try {
      const generatedAt = new Date().toISOString();
      // Each format gets a timestamped entry so history is preserved
      const newFormatEntry = {
        type: publishOptions.format, // 'pdf', 'excel', 'landing_page'
        generatedAt,
        priceLevel: publishOptions.priceLevel,
        showPrices: publishOptions.showPrices,
        pdfTemplate:
          publishOptions.format === 'pdf' || publishOptions.format === 'landing_page'
            ? publishOptions.pdfTemplate
            : null,
      };

      const catalogData = {
        ...emptyCatalog({ ownerId: tenantId, ownerType: 'wholesaler' }),
        title: catalogMeta.title,
        description: catalogMeta.description,
        status: CATALOG_STATUS.PUBLISHED,
        selectedProducts: catalogCart,
        sections: [{ title: 'Main Catalog', products: catalogCart, protocols: [] }],
        date: catalogMeta.date,
        targetAudience: catalogMeta.targetAudience,
        cartProductsSnapshot: cartProducts.filter(
          (p) => catalogCart.includes(p.id) || catalogCart.includes(p.productId)
        ),
        // formats: array of all format generations for this catalog
        formats: [newFormatEntry],
        pdfTemplate: publishOptions.pdfTemplate, // Top level field added to Canonical fields
        createdAt: generatedAt,
        updatedAt: generatedAt,
      };

      // If PDF, run generator
      if (publishOptions.format === 'pdf') {
        try {
          const tenantInfo = { name: 'Atlas Health' }; // Or fetch from context
          const blob = await generateCatalogPdf(catalogData, publishOptions, tenantInfo, {
            onProgress: (p) =>
              setGenerationState({
                isGenerating: true,
                step: p.step,
                progress: p.progress,
                message: p.message,
              }),
          });
          downloadPdfBlob(blob, `${catalogMeta.title.replace(/\s+/g, '_')}.pdf`);
        } catch (pdfErr) {
          console.error('PDF Generation error:', pdfErr);
          toast.error('Failed to generate PDF');
          setGenerationState({ isGenerating: false, step: 0 });
          return;
        }
      }

      // If Excel, run generator
      if (publishOptions.format === 'excel') {
        try {
          const blob = generateCatalogExcel(catalogData, publishOptions);
          downloadExcelBlob(blob, `${catalogMeta.title.replace(/\s+/g, '_')}.xlsx`);
        } catch (excelErr) {
          console.error('Excel Generation error:', excelErr);
          toast.error('Failed to generate Excel');
          return;
        }
      }

      const result = await catalogRepository.saveCatalog(catalogData);
      if (result) {
        toast.success(
          `Catalog published successfully as ${publishOptions.format.replace('_', ' ')}!`
        );

        // Execute sharing action if config is provided
        if (shareConfig) {
          const catalogUrl = `${window.location.origin}/catalog/${result.slug}`;

          if (shareConfig.channel === 'whatsapp') {
            const encodedText = encodeURIComponent(
              shareConfig.text || `Hello! Here is our catalog: ${catalogUrl}`
            );
            const phone = shareConfig.phone.replace(/[^0-9]/g, '');
            const waUrl = `https://wa.me/${phone}?text=${encodedText}`;
            window.open(waUrl, '_blank');
            toast.success('Opened WhatsApp sharing link!');
          } else if (shareConfig.channel === 'email') {
            toast.success(`Catalog successfully emailed to ${shareConfig.recipient}!`);
          } else if (shareConfig.channel === 'bigin') {
            toast.success(
              `Catalog notes synced to Zoho Bigin Contact: ${shareConfig.contactEmail}!`
            );
          }
        }

        setShowPublishOptions(false);
        setShowPreviewModal(false);
        setGenerationState({ isGenerating: false, step: 0 });
        clearDraft(); // Clear persistent draft
        if (onBack) onBack();
        else router.push(ownerType === 'admin' ? '/admin/products' : '/wholesaler/catalogs');
      }
    } catch (err) {
      console.error(err);
      toast.error('Failed to save catalog');
      setGenerationState({ isGenerating: false, step: 0 });
    }
  };

  const handleOpenPreview = async () => {
    if (!catalogMeta.title) {
      toast.error('Catalog must have a title');
      return;
    }
    setShowPreviewModal(true);

    // Prefill share fields
    setShareEmailSubject(`Atlas Health Catalog - ${catalogMeta.title}`);
    setShareEmailBody(
      `Hello,\n\nI am sharing our latest clinical catalog "${catalogMeta.title}" with you. You can access it through the secure portal.\n\nBest regards,\nJose`
    );
    setShareWhatsAppText(`Hello! Here is the link to our new catalog "${catalogMeta.title}": `);

    if (publishOptions.format === 'pdf') {
      setGeneratingPreview(true);
      try {
        const generatedAt = new Date().toISOString();
        const catalogData = {
          title: catalogMeta.title,
          description: catalogMeta.description,
          status: CATALOG_STATUS.PUBLISHED,
          selectedProducts: catalogCart,
          sections: [{ title: 'Main Catalog', products: catalogCart, protocols: [] }],
          date: catalogMeta.date,
          targetAudience: catalogMeta.targetAudience,
          cartProductsSnapshot: cartProducts.filter(
            (p) => catalogCart.includes(p.id) || catalogCart.includes(p.productId)
          ),
          formats: [],
          pdfTemplate: publishOptions.pdfTemplate,
          createdAt: generatedAt,
          updatedAt: generatedAt,
        };
        const tenantInfo = { name: 'Atlas Health' };
        const blob = await generateCatalogPdf(catalogData, publishOptions, tenantInfo, {
          onProgress: () => {},
        });
        if (previewBlobUrl) {
          URL.revokeObjectURL(previewBlobUrl);
        }
        const url = URL.createObjectURL(blob);
        setPreviewBlobUrl(url);
      } catch (err) {
        console.error('Failed to generate PDF preview:', err);
        toast.error('Failed to generate PDF preview');
      } finally {
        setGeneratingPreview(false);
      }
    }
  };

  return (
    <>
      <SmartCatalogWelcomeModal
        isOpen={showWelcomeModal}
        selectedCount={location.state?.selectedProducts?.length || 0}
        filteredCount={location.state?.filteredProducts?.length || 0}
        onSelect={handleWelcomeSelection}
      />

      <div
        style={{ height: '100vh', display: 'flex', flexDirection: 'column', background: '#fff' }}
      >
        {/* Header */}
        <header
          style={{
            height: '64px',
            borderBottom: '1px solid #e2e8f0',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '0 24px',
            background: '#fff',
            zIndex: 50,
            position: 'sticky',
            top: 0,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <button
              onClick={() => (onBack ? onBack() : router.back())}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '8px 16px',
                borderRadius: '8px',
                background: '#f8fafc',
                color: '#64748b',
                border: '1px solid #e2e8f0',
                fontWeight: 600,
                fontSize: '0.85rem',
                cursor: 'pointer',
                transition: 'all 0.2s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = '#f1f5f9';
                e.currentTarget.style.borderColor = '#cbd5e1';
                e.currentTarget.style.color = '#475569';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = '#f8fafc';
                e.currentTarget.style.borderColor = '#e2e8f0';
                e.currentTarget.style.color = '#64748b';
              }}
            >
              <ArrowLeft size={16} /> Back to Hub
            </button>
            <div
              style={{ width: '1px', height: '24px', background: '#e2e8f0', margin: '0 24px' }}
            ></div>
            <h2 style={{ margin: 0, fontSize: '1.125rem', fontWeight: 600, color: '#0f172a' }}>
              {catalogMeta.title || 'Untitled Catalog'}{' '}
              <span
                style={{
                  marginLeft: '12px',
                  fontSize: '0.8rem',
                  background: '#f1f5f9',
                  padding: '4px 8px',
                  borderRadius: '12px',
                  color: '#64748b',
                }}
              >
                Draft
              </span>{' '}
              <span style={{ marginLeft: '8px', fontSize: '0.8rem', color: '#64748b' }}>
                {cartProducts.length} Products
              </span>
            </h2>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <button
              onClick={() => setShowAIDrawer(true)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                padding: '8px 16px',
                borderRadius: '8px',
                background: '#f8fafc',
                color: '#6366f1',
                border: '1px solid #e0e7ff',
                fontWeight: 600,
                fontSize: '0.85rem',
                cursor: 'pointer',
                transition: 'all 0.2s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = '#eef2ff';
                e.currentTarget.style.borderColor = '#c7d2fe';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = '#f8fafc';
                e.currentTarget.style.borderColor = '#e0e7ff';
              }}
            >
              <SparklesIcon size={16} /> AI Assistant
            </button>
            <button
              onClick={() => setShowPublishOptions(true)}
              disabled={catalogCart.length === 0 || !catalogMeta.title}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                padding: '8px 16px',
                borderRadius: '8px',
                background: catalogCart.length === 0 || !catalogMeta.title ? '#cbd5e1' : '#1e293b',
                color: '#fff',
                border: 'none',
                fontWeight: 600,
                fontSize: '0.85rem',
                cursor: catalogCart.length === 0 || !catalogMeta.title ? 'not-allowed' : 'pointer',
                transition: 'all 0.2s',
              }}
              onMouseEnter={(e) => {
                if (catalogCart.length > 0 && catalogMeta.title) {
                  e.currentTarget.style.backgroundColor = '#0f172a';
                }
              }}
              onMouseLeave={(e) => {
                if (catalogCart.length > 0 && catalogMeta.title) {
                  e.currentTarget.style.backgroundColor = '#1e293b';
                }
              }}
            >
              Publish Catalog
            </button>
          </div>
        </header>

        {/* Main Layout */}
        <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
          {isMobile ? (
            <div style={{ padding: '24px', width: '100%', overflowY: 'auto' }}>
              {mobileStep === 1 && (
                <CatalogAIAssistantPanel
                  catalogMeta={catalogMeta}
                  setCatalogMeta={setCatalogMeta}
                  isGeneratingAI={isGeneratingAI}
                  onGenerateAI={handleGenerateSmartCatalog}
                  catalogCart={catalogCart}
                />
              )}
              {mobileStep === 2 && <CenterPanel
        catalogCart={catalogCart}
        catalogMeta={catalogMeta}
        ownerType={ownerType}
        activeAccordionOpen={activeAccordionOpen}
        setActiveAccordionOpen={setActiveAccordionOpen}
        publishedAccordionOpen={publishedAccordionOpen}
        setPublishedAccordionOpen={setPublishedAccordionOpen}
        matrixViewType={matrixViewType}
        setMatrixViewType={setMatrixViewType}
        tableProducts={tableProducts}
        loading={loading}
        currentPage={currentPage}
        setPage={setPage}
        rowsPerPage={rowsPerPage}
        setRowsPerPage={setRowsPerPage}
        handleSelectionChange={handleSelectionChange}
        pastCatalogs={pastCatalogs}
        loadPastCatalog={loadPastCatalog}
        router={router}
      />}
              {mobileStep === 3 && (
                <CatalogIntelligenceDrawer
                  isOpen={true}
                  setIsOpen={() => {}}
                  catalogCart={catalogCart}
                  allProducts={allProducts}
                />
              )}

              <div
                style={{
                  position: 'fixed',
                  bottom: 0,
                  left: 0,
                  right: 0,
                  padding: '16px',
                  background: '#fff',
                  borderTop: '1px solid #e2e8f0',
                  display: 'flex',
                  justifyContent: 'space-between',
                }}
              >
                <button
                  onClick={() => setMobileStep((prev) => Math.max(1, prev - 1))}
                  disabled={mobileStep === 1}
                  style={{
                    padding: '12px 24px',
                    border: '1px solid #cbd5e1',
                    borderRadius: '8px',
                    background: '#fff',
                  }}
                >
                  Back
                </button>
                <button
                  onClick={() => setMobileStep((prev) => Math.min(3, prev + 1))}
                  disabled={mobileStep === 3}
                  style={{
                    padding: '12px 24px',
                    border: 'none',
                    borderRadius: '8px',
                    background: '#1e293b',
                    color: '#fff',
                  }}
                >
                  Next
                </button>
              </div>
            </div>
          ) : (
            <>
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
                <CenterPanel
        catalogCart={catalogCart}
        catalogMeta={catalogMeta}
        ownerType={ownerType}
        activeAccordionOpen={activeAccordionOpen}
        setActiveAccordionOpen={setActiveAccordionOpen}
        publishedAccordionOpen={publishedAccordionOpen}
        setPublishedAccordionOpen={setPublishedAccordionOpen}
        matrixViewType={matrixViewType}
        setMatrixViewType={setMatrixViewType}
        tableProducts={tableProducts}
        loading={loading}
        currentPage={currentPage}
        setPage={setPage}
        rowsPerPage={rowsPerPage}
        setRowsPerPage={setRowsPerPage}
        handleSelectionChange={handleSelectionChange}
        pastCatalogs={pastCatalogs}
        loadPastCatalog={loadPastCatalog}
        router={router}
      />
              </div>
            </>
          )}
        </div>
      </div>

      <AnimatePresence>
        {showAIDrawer && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 0.5 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowAIDrawer(false)}
              style={{
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background: '#000',
                zIndex: 9998,
              }}
            />
            <motion.div
              initial={{ x: '-100%' }}
              animate={{ x: 0 }}
              exit={{ x: '-100%' }}
              transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
              style={{
                position: 'fixed',
                top: 0,
                left: 0,
                bottom: 0,
                width: '100%',
                maxWidth: '350px',
                background: '#fff',
                zIndex: 9999,
                display: 'flex',
                flexDirection: 'column',
                boxShadow: '10px 0 25px rgba(0, 0, 0, 0.1)',
              }}
            >
              <div
                style={{
                  padding: '24px',
                  borderBottom: '1px solid #e2e8f0',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <h2 style={{ margin: 0, fontSize: '1.25rem', color: '#0f172a', fontWeight: 600 }}>
                  AI Assistant
                </h2>
                <button
                  onClick={() => setShowAIDrawer(false)}
                  style={{
                    background: '#f1f5f9',
                    border: 'none',
                    cursor: 'pointer',
                    color: '#64748b',
                    width: '32px',
                    height: '32px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    transition: 'background 0.2s',
                  }}
                >
                  <X size={18} />
                </button>
              </div>
              <div style={{ flex: 1, overflowY: 'auto' }}>
                <CatalogAIAssistantPanel
                  catalogMeta={catalogMeta}
                  setCatalogMeta={setCatalogMeta}
                  isGeneratingAI={isGeneratingAI}
                  onGenerateAI={handleGenerateSmartCatalog}
                  catalogCart={catalogCart}
                />
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {generationState.isGenerating && (
          <div
            style={{
              position: 'fixed',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              background: 'rgba(0,0,0,0.6)',
              zIndex: 10000,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              backdropFilter: 'blur(4px)',
            }}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              style={{
                background: '#fff',
                borderRadius: '16px',
                padding: '32px',
                width: '90%',
                maxWidth: '400px',
                boxShadow:
                  '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
              }}
            >
              <div style={{ textAlign: 'center', marginBottom: '24px' }}>
                <div
                  style={{
                    width: '48px',
                    height: '48px',
                    borderRadius: '50%',
                    background: '#f0fdf4',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    margin: '0 auto 16px auto',
                  }}
                >
                  <SparklesIcon size={24} color="#16a34a" />
                </div>
                <h3 style={{ margin: '0 0 8px 0', fontSize: '1.25rem', color: '#0f172a' }}>
                  Generating Artifacts
                </h3>
                <p style={{ margin: 0, color: '#64748b', fontSize: '0.95rem' }}>
                  Please wait while we compile your catalog formats.
                </p>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                {GENERATION_STEPS.map((stepName, idx) => {
                  const isActive = idx === generationState.step;
                  const isDone = idx < generationState.step;
                  return (
                    <div
                      key={idx}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '12px',
                        opacity: isActive || isDone ? 1 : 0.4,
                      }}
                    >
                      <div
                        style={{
                          width: '24px',
                          height: '24px',
                          borderRadius: '50%',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          background: isDone ? '#16a34a' : isActive ? '#3b82f6' : '#e2e8f0',
                          color: '#fff',
                          fontSize: '0.75rem',
                          fontWeight: 'bold',
                          transition: 'all 0.3s',
                        }}
                      >
                        {isDone ? '✓' : idx + 1}
                      </div>
                      <span
                        style={{
                          fontSize: '0.9rem',
                          color: isDone || isActive ? '#0f172a' : '#64748b',
                          fontWeight: isActive ? 600 : 400,
                        }}
                      >
                        {stepName}
                      </span>
                    </div>
                  );
                })}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {showPublishOptions && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 0.5 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowPublishOptions(false)}
              style={{
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background: '#000',
                zIndex: 9998,
              }}
            />
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
              style={{
                position: 'fixed',
                top: 0,
                right: 0,
                bottom: 0,
                width: '100%',
                maxWidth: '480px',
                background: '#fff',
                zIndex: 9999,
                display: 'flex',
                flexDirection: 'column',
                boxShadow: '-10px 0 25px rgba(0, 0, 0, 0.1)',
              }}
            >
              {/* Drawer Header */}
              <div
                style={{
                  padding: '24px',
                  borderBottom: '1px solid #e2e8f0',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <h2 style={{ margin: 0, fontSize: '1.25rem', color: '#0f172a', fontWeight: 600 }}>
                  Publish Options
                </h2>
                <button
                  onClick={() => setShowPublishOptions(false)}
                  style={{
                    background: '#f1f5f9',
                    border: 'none',
                    cursor: 'pointer',
                    color: '#64748b',
                    width: '32px',
                    height: '32px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    transition: 'background 0.2s',
                  }}
                >
                  <X size={18} />
                </button>
              </div>

              {/* Drawer Content */}
              <div
                style={{
                  padding: '24px',
                  flex: 1,
                  overflowY: 'auto',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '24px',
                }}
              >
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  <div>
                    <label
                      style={{
                        display: 'block',
                        marginBottom: '8px',
                        fontWeight: 600,
                        fontSize: '0.9rem',
                        color: '#334155',
                      }}
                    >
                      Catalog Title
                    </label>
                    <input
                      type="text"
                      value={catalogMeta.title}
                      onChange={(e) =>
                        setCatalogMeta((prev) => ({ ...prev, title: e.target.value }))
                      }
                      placeholder="e.g., Summer Medical Supplies"
                      style={{
                        width: '100%',
                        fontSize: '1rem',
                        color: '#0f172a',
                        border: '1px solid #cbd5e1',
                        borderRadius: '6px',
                        padding: '10px',
                        outline: 'none',
                      }}
                    />
                  </div>
                  <div>
                    <label
                      style={{
                        display: 'block',
                        marginBottom: '8px',
                        fontWeight: 600,
                        fontSize: '0.9rem',
                        color: '#334155',
                      }}
                    >
                      Description
                    </label>
                    <textarea
                      value={catalogMeta.description}
                      onChange={(e) =>
                        setCatalogMeta((prev) => ({ ...prev, description: e.target.value }))
                      }
                      placeholder="Commercial description of your portfolio..."
                      rows={2}
                      style={{
                        width: '100%',
                        fontSize: '0.95rem',
                        color: '#475569',
                        border: '1px solid #cbd5e1',
                        borderRadius: '6px',
                        padding: '10px',
                        outline: 'none',
                        resize: 'none',
                      }}
                    />
                  </div>
                  <div style={{ display: 'flex', gap: '12px' }}>
                    <div style={{ flex: 1 }}>
                      <label
                        style={{
                          display: 'block',
                          marginBottom: '8px',
                          fontWeight: 600,
                          fontSize: '0.9rem',
                          color: '#334155',
                        }}
                      >
                        Date
                      </label>
                      <input
                        type="date"
                        value={catalogMeta.date}
                        onChange={(e) =>
                          setCatalogMeta((prev) => ({ ...prev, date: e.target.value }))
                        }
                        style={{
                          width: '100%',
                          padding: '10px',
                          border: '1px solid #cbd5e1',
                          borderRadius: '6px',
                          fontSize: '0.95rem',
                          background: '#fff',
                        }}
                      />
                    </div>
                    <div style={{ flex: 1 }}>
                      <label
                        style={{
                          display: 'block',
                          marginBottom: '8px',
                          fontWeight: 600,
                          fontSize: '0.9rem',
                          color: '#334155',
                        }}
                      >
                        Audience
                      </label>
                      <select
                        value={catalogMeta.targetAudience}
                        onChange={(e) =>
                          setCatalogMeta((prev) => ({ ...prev, targetAudience: e.target.value }))
                        }
                        style={{
                          width: '100%',
                          padding: '10px',
                          border: '1px solid #cbd5e1',
                          borderRadius: '6px',
                          fontSize: '0.95rem',
                          background: '#fff',
                        }}
                      >
                        <option value="patients">Patients</option>
                        <option value="doctors">Doctors / Clinics</option>
                        <option value="wholesalers">Wholesalers</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div
                  style={{
                    background: '#f8fafc',
                    padding: '16px',
                    borderRadius: '8px',
                    border: '1px solid #e2e8f0',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '12px',
                  }}
                >
                  <div
                    style={{
                      fontSize: '0.9rem',
                      fontWeight: 600,
                      color: '#334155',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px',
                    }}
                  >
                    <Percent size={14} /> Pricing Multiplier Strategy
                  </div>
                  <p style={{ fontSize: '0.8rem', color: '#64748b', margin: '0 0 4px 0' }}>
                    Adjust prices globally.{' '}
                    <i>Note: All prices are ex-works, shipping not included.</i>
                  </p>
                  <div
                    style={{ display: 'flex', gap: '8px', alignItems: 'center', flexWrap: 'wrap' }}
                  >
                    <select
                      value={pricingMultiplier.basePriceKey}
                      onChange={(e) =>
                        setPricingMultiplier((prev) => ({ ...prev, basePriceKey: e.target.value }))
                      }
                      style={{
                        flex: 1,
                        padding: '8px',
                        border: '1px solid #cbd5e1',
                        borderRadius: '6px',
                        fontSize: '0.85rem',
                      }}
                    >
                      <option value="cost">Base: Cost</option>
                      <option value="price">Base: Retail Price</option>
                    </select>
                    <span style={{ color: '#94a3b8' }}>+</span>
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        border: '1px solid #cbd5e1',
                        borderRadius: '6px',
                        background: '#fff',
                        overflow: 'hidden',
                        width: '80px',
                      }}
                    >
                      <input
                        type="number"
                        value={pricingMultiplier.incrementPercent}
                        onChange={(e) =>
                          setPricingMultiplier((prev) => ({
                            ...prev,
                            incrementPercent: e.target.value,
                          }))
                        }
                        style={{
                          width: '100%',
                          padding: '8px',
                          border: 'none',
                          outline: 'none',
                          textAlign: 'right',
                          fontSize: '0.85rem',
                        }}
                      />
                      <span
                        style={{
                          padding: '8px',
                          background: '#f1f5f9',
                          color: '#64748b',
                          fontSize: '0.85rem',
                          borderLeft: '1px solid #cbd5e1',
                        }}
                      >
                        %
                      </span>
                    </div>
                    <button
                      onClick={applyMultiplier}
                      style={{
                        padding: '8px 12px',
                        background: '#1e293b',
                        color: '#fff',
                        border: 'none',
                        borderRadius: '6px',
                        fontSize: '0.85rem',
                        fontWeight: 600,
                        cursor: 'pointer',
                      }}
                    >
                      Apply
                    </button>
                  </div>
                </div>

                <hr style={{ border: 'none', borderTop: '1px solid #e2e8f0', margin: '8px 0' }} />

                <div>
                  <label
                    style={{
                      display: 'block',
                      marginBottom: '8px',
                      fontWeight: 600,
                      fontSize: '0.9rem',
                      color: '#334155',
                    }}
                  >
                    Publish Format
                  </label>
                  <select
                    value={publishOptions.format}
                    onChange={(e) =>
                      setPublishOptions({ ...publishOptions, format: e.target.value })
                    }
                    style={{
                      width: '100%',
                      padding: '12px',
                      borderRadius: '8px',
                      border: '1px solid #cbd5e1',
                      fontSize: '0.95rem',
                      background: '#f8fafc',
                      outline: 'none',
                    }}
                  >
                    <option value="landing_page">Interactive Landing Page</option>
                    <option value="pdf">PDF Document</option>
                    <option value="excel">Excel Spreadsheet</option>
                  </select>
                </div>

                {(publishOptions.format === 'pdf' || publishOptions.format === 'landing_page') && (
                  <div
                    style={{
                      background: '#f8fafc',
                      padding: '16px',
                      borderRadius: '8px',
                      border: '1px solid #e2e8f0',
                    }}
                  >
                    <label
                      style={{
                        display: 'block',
                        marginBottom: '12px',
                        fontWeight: 600,
                        color: '#334155',
                      }}
                    >
                      <LayoutTemplate
                        size={16}
                        style={{
                          display: 'inline-block',
                          verticalAlign: 'middle',
                          marginRight: '8px',
                          color: '#64748b',
                        }}
                      />
                      Select Template Style
                    </label>
                    <div
                      style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '8px' }}
                    >
                      {[
                        { id: 'minimal', label: 'Minimal', desc: 'Photos & Price' },
                        { id: 'standard', label: 'Standard', desc: 'General Info' },
                        { id: 'clinical', label: 'Clinical', desc: 'AI Enriched' },
                      ].map((t) => (
                        <div
                          key={t.id}
                          onClick={() =>
                            setPublishOptions({ ...publishOptions, pdfTemplate: t.id })
                          }
                          style={{
                            padding: '12px 8px',
                            borderRadius: '6px',
                            border: `2px solid ${publishOptions.pdfTemplate === t.id ? '#2563eb' : '#cbd5e1'}`,
                            background: publishOptions.pdfTemplate === t.id ? '#eff6ff' : '#fff',
                            cursor: 'pointer',
                            textAlign: 'center',
                            transition: 'all 0.2s',
                          }}
                        >
                          <div
                            style={{
                              fontWeight: 600,
                              fontSize: '0.9rem',
                              color: publishOptions.pdfTemplate === t.id ? '#1e40af' : '#475569',
                            }}
                          >
                            {t.label}
                          </div>
                          <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '4px' }}>
                            {t.desc}
                          </div>
                          {t.id === 'clinical' && (
                            <div
                              style={{
                                fontSize: '0.7rem',
                                color: '#8b5cf6',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                gap: '4px',
                                marginTop: '6px',
                                fontWeight: 500,
                              }}
                            >
                              <SparklesIcon size={10} /> AI Powered
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div
                  style={{
                    background: '#f8fafc',
                    padding: '16px',
                    borderRadius: '8px',
                    border: '1px solid #e2e8f0',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '16px',
                  }}
                >
                  <label
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '10px',
                      cursor: 'pointer',
                    }}
                  >
                    <input
                      type="checkbox"
                      checked={publishOptions.showPrices}
                      onChange={(e) =>
                        setPublishOptions({ ...publishOptions, showPrices: e.target.checked })
                      }
                      style={{ width: '18px', height: '18px', cursor: 'pointer' }}
                    />
                    <span style={{ fontWeight: 600, color: '#334155' }}>Include Pricing</span>
                  </label>

                  {publishOptions.showPrices && (
                    <div style={{ paddingLeft: '28px', animation: 'fadeIn 0.2s ease-out' }}>
                      <label
                        style={{
                          display: 'block',
                          marginBottom: '8px',
                          fontWeight: 500,
                          fontSize: '0.85rem',
                          color: '#64748b',
                        }}
                      >
                        Select Price Level
                      </label>
                      <select
                        value={publishOptions.priceLevel}
                        onChange={(e) =>
                          setPublishOptions({ ...publishOptions, priceLevel: e.target.value })
                        }
                        style={{
                          width: '100%',
                          padding: '10px',
                          borderRadius: '6px',
                          border: '1px solid #cbd5e1',
                          fontSize: '0.95rem',
                          background: '#fff',
                          outline: 'none',
                        }}
                      >
                        <option value="MSRP">MSRP (Retail)</option>
                        <option value="wholesale">Wholesale</option>
                        <option value="custom">Custom Margin (+20%)</option>
                      </select>
                    </div>
                  )}
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <label
                    style={{
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '10px',
                      cursor: 'pointer',
                    }}
                  >
                    <input
                      type="checkbox"
                      checked={publishOptions.includeContactData}
                      onChange={(e) =>
                        setPublishOptions({
                          ...publishOptions,
                          includeContactData: e.target.checked,
                        })
                      }
                      style={{ width: '18px', height: '18px', marginTop: '2px', cursor: 'pointer' }}
                    />
                    <div>
                      <div style={{ fontWeight: 600, color: '#334155' }}>Include Contact Info</div>
                      <div style={{ fontSize: '0.8rem', color: '#64748b', marginTop: '2px' }}>
                        Uses your default tenant contact data.
                      </div>
                    </div>
                  </label>
                </div>
              </div>

              {/* Drawer Footer */}
              <div
                style={{
                  padding: '24px',
                  borderTop: '1px solid #e2e8f0',
                  display: 'flex',
                  gap: '12px',
                  background: '#f8fafc',
                }}
              >
                <button
                  onClick={() => setShowPublishOptions(false)}
                  style={{
                    flex: 1,
                    padding: '12px 16px',
                    background: '#fff',
                    border: '1px solid #cbd5e1',
                    borderRadius: '8px',
                    fontWeight: 600,
                    color: '#475569',
                    cursor: 'pointer',
                    transition: 'background 0.2s',
                  }}
                  onMouseOver={(e) => (e.target.style.background = '#f1f5f9')}
                  onMouseOut={(e) => (e.target.style.background = '#fff')}
                >
                  Cancel
                </button>
                <button
                  onClick={handleOpenPreview}
                  style={{
                    flex: 1,
                    padding: '12px 16px',
                    background: '#2563eb',
                    border: 'none',
                    borderRadius: '8px',
                    fontWeight: 600,
                    color: '#fff',
                    cursor: 'pointer',
                    transition: 'background 0.2s',
                  }}
                  onMouseOver={(e) => (e.target.style.background = '#1d4ed8')}
                  onMouseOut={(e) => (e.target.style.background = '#2563eb')}
                >
                  Preview & Share
                </button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Extracted Preview & Share Modal */}
      <CatalogPreviewAndShareModal
        showPreviewModal={showPreviewModal}
        setShowPreviewModal={setShowPreviewModal}
        previewBlobUrl={previewBlobUrl}
        setPreviewBlobUrl={setPreviewBlobUrl}
        catalogMeta={catalogMeta}
        publishOptions={publishOptions}
        generatingPreview={generatingPreview}
        cartProducts={cartProducts}
        catalogCart={catalogCart}
        activeShareTab={activeShareTab}
        setActiveShareTab={setActiveShareTab}
        shareEmail={shareEmail}
        setShareEmail={setShareEmail}
        shareEmailSubject={shareEmailSubject}
        setShareEmailSubject={setShareEmailSubject}
        shareEmailBody={shareEmailBody}
        setShareEmailBody={setShareEmailBody}
        saveCatalog={saveCatalog}
        sharePhone={sharePhone}
        setSharePhone={setSharePhone}
        shareWhatsAppText={shareWhatsAppText}
        setShareWhatsAppText={setShareWhatsAppText}
        shareBiginEmail={shareBiginEmail}
        setShareBiginEmail={setShareBiginEmail}
        shareBiginStage={shareBiginStage}
        setShareBiginStage={setShareBiginStage}
        shareBiginNotes={shareBiginNotes}
        setShareBiginNotes={setShareBiginNotes}
        biginSyncing={biginSyncing}
        setBiginSyncing={setBiginSyncing}
        toast={toast}
      />
    </>
  );
}
