const { onSchedule } = require("firebase-functions/v2/scheduler");
const { getFirestore } = require("firebase-admin/firestore");
const nodemailer = require("nodemailer");
const { gmailUser, gmailAppPass } = require("../config");

exports.weeklyCompetitorDigest = onSchedule({
  schedule: "0 8 * * 1", // Every Monday at 8:00 AM
  timeZone: "Asia/Dubai",
  timeoutSeconds: 300,
  secrets: [gmailUser, gmailAppPass]
}, async (event) => {
  console.log("[weeklyCompetitorDigest] Starting weekly digest generation...");
  const db = getFirestore();
  
  try {
    const cacheDoc = await db.collection("settings").doc("competitor_cache").get();
    if (!cacheDoc.exists) {
      console.log("[weeklyCompetitorDigest] No competitor cache found, aborting.");
      return;
    }
    
    const cacheData = cacheDoc.data();
    const matches = cacheData.matches || [];
    
    // We will analyze the "retail" tier by default for the email summary
    let cheaperCount = 0;
    let expensiveCount = 0;
    let totalMatches = matches.length;
    let topPriceDropsHtml = "";
    let alertsHtml = "";
    
    const drops = [];

    matches.forEach(match => {
      const myPPM = match.myPPMs ? match.myPPMs["retail"] : null;
      let isOverallCheaper = true;
      let isOverallExpensive = true;
      
      if (myPPM) {
        match.competitors.forEach(comp => {
          const compPPM = comp.ppm;
          if (compPPM) {
            const diff = myPPM - compPPM;
            if (diff > 0.05) isOverallCheaper = false; // We are more expensive
            if (diff < -0.05) isOverallExpensive = false; // We are cheaper
          }
          
          if (comp.trend === 'down' && comp.price_diff_vs_yesterday < 0) {
             drops.push(`<li style="padding: 4px 0;"><strong>${comp.competitor_name}</strong> dropped the price of <strong>${comp.product_name}</strong> by $${Math.abs(comp.price_diff_vs_yesterday).toFixed(2)}</li>`);
          }
        });

        if (isOverallCheaper && !isOverallExpensive) cheaperCount++;
        if (isOverallExpensive && !isOverallCheaper) expensiveCount++;
      }
    });

    if (drops.length > 0) {
      topPriceDropsHtml = drops.slice(0, 10).join("");
    } else {
      topPriceDropsHtml = "<li style='padding: 4px 0;'>No significant price drops detected in the market this week.</li>";
    }

    if (expensiveCount > 0) {
      alertsHtml = `<div style="background: #fef2f2; padding: 16px 20px; border-radius: 8px; border: 1px solid #fecaca; margin-top: 24px;">
        <p style="margin: 0 0 8px 0; font-weight: 700; color: #b91c1c;">⚠️ Pricing Alert</p>
        <p style="margin: 0; color: #7f1d1d; font-size: 14px;">You have <strong>${expensiveCount} products</strong> where the Retail price is less competitive than the market average. We recommend reviewing the Atlas AI Competitors dashboard to adjust your selling prices or review production costs.</p>
      </div>`;
    }

    const user = gmailUser.value();
    const pass = gmailAppPass.value();
    
    if (!user || !pass) {
      console.warn("[weeklyCompetitorDigest] Gmail credentials missing.");
      return;
    }

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: { user, pass }
    });

    const baseUrl = 'https://med-peptides-app-27a3a.web.app';
    const logoUrl = `${baseUrl}/logo.png`; 

    const html = `
      <div style="font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #334155; max-width: 600px; margin: 0 auto; line-height: 1.6; background-color: #ffffff; border-radius: 12px; padding: 32px; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.1), 0 8px 10px -6px rgba(0,0,0,0.1); border: 1px solid #e2e8f0;">
        <div style="text-align: center; border-bottom: 2px solid #f1f5f9; padding-bottom: 24px; margin-bottom: 24px;">
          <h1 style="color: #0f172a; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px;">ATLAS HEALTH</h1>
          <p style="color: #64748b; margin: 4px 0 0 0; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Weekly Competitor Digest</p>
        </div>
        
        <p style="font-size: 16px;">Hi José,</p>
        <p style="font-size: 16px;">Here is the weekly analysis of the Vials and Peptides market generated by your Atlas AI tool.</p>
        
        <div style="margin-bottom: 28px;">
          <h3 style="color: #3b82f6; display: flex; align-items: center; justify-content: space-between; font-size: 18px; margin-bottom: 12px;">
            <span>📊 Global Metrics (Retail)</span>
          </h3>
          <ul style="background: #f8fafc; padding: 16px 20px 16px 36px; border-radius: 8px; margin: 0; border: 1px solid #f1f5f9; list-style-type: disc;">
            <li style="padding: 4px 0;">Products matched with competitors: <strong>${totalMatches}</strong></li>
            <li style="padding: 4px 0;">Highly Competitive Products (You are the cheapest): <strong style="color: #10b981;">${cheaperCount}</strong></li>
            <li style="padding: 4px 0;">Less Competitive Products (You are the most expensive): <strong style="color: #ef4444;">${expensiveCount}</strong></li>
          </ul>
        </div>
        
        ${alertsHtml}

        <div style="margin-bottom: 28px; margin-top: 28px;">
          <h3 style="color: #f59e0b; display: flex; align-items: center; justify-content: space-between; font-size: 18px; margin-bottom: 12px;">
            <span>📉 Market Movements</span>
          </h3>
          <ul style="background: #f8fafc; padding: 16px 20px 16px 36px; border-radius: 8px; margin: 0; border: 1px solid #f1f5f9;">
            ${topPriceDropsHtml}
          </ul>
        </div>

        <div style="text-align: center; margin-top: 40px; margin-bottom: 10px;">
          <a href="${baseUrl}/admin/competitors" style="display: inline-block; background-color: #0f172a; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 16px; letter-spacing: 0.5px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">View Competitors Dashboard</a>
        </div>

        <p style="margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 24px; line-height: 1.5;">
          This is an automatically generated message from the Atlas Health System Administration.<br/>
        </p>
      </div>
    `;

    await transporter.sendMail({
      from: `"Atlas Health Admin" <${user}>`,
      to: "jose@mediluxeme.com",
      subject: `Weekly Competitor Digest - Atlas Health`,
      html: html
    });
    
    console.log(`[weeklyCompetitorDigest] Email digest sent successfully.`);
  } catch (err) {
    console.error("[weeklyCompetitorDigest] Error generating digest:", err);
  }
});
