/* eslint-disable no-unused-vars */
import { jsPDF } from "jspdf";

export async function generateClinicalBriefPDF(messages = []) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 20;
  let pageCount = 1;

  const addHeader = (isFirstPage) => {
    // Atlas Health Header Banner
    doc.setFillColor(0, 54, 102); // Deep corporate blue
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Logo / Title
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("ATLAS HEALTH", 20, 25);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(200, 210, 225);
    doc.text("Clinical Intelligence Report", 20, 35);
    
    // Timestamp
    doc.setFontSize(9);
    doc.text(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth - 20, 25, { align: 'right' });
    doc.text(`Time: ${new Date().toLocaleTimeString('en-US')}`, pageWidth - 20, 32, { align: 'right' });
    
    // Watermark line
    doc.setDrawColor(13, 148, 136); // Teal accent
    doc.setLineWidth(1.5);
    doc.line(0, 45, pageWidth, 45);
    
    y = 65;
  };

  const addFooter = () => {
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.5);
    doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);
    
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("Confidential Clinical Report generated by Atlas AI.", 20, pageHeight - 12);
    doc.text(`Page ${pageCount}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
    doc.text("For informational purposes only. Verify with medical professional.", pageWidth / 2, pageHeight - 12, { align: "center" });
  };

  addHeader(true);

  messages.forEach((msg, index) => {
    if (msg.role === 'system' || msg.content === '...') return; // Skip system and thinking messages

    const isUser = msg.role === 'user';
    
    // Message Box / Bubble
    if (y > pageHeight - 40) {
      addFooter();
      doc.addPage();
      pageCount++;
      addHeader(false);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(isUser ? 13 : 0, isUser ? 148 : 54, isUser ? 136 : 102); // Teal for user, Blue for AI
    doc.text(isUser ? "RESEARCHER QUERY" : "ATLAS AI ANALYSIS", 20, y);
    y += 6;

    // Clean text
    let cleanText = msg.content
      .replace(/\[EVIDENCE:.*?\]/gi, '')
      .replace(/\[STACK_SYNERGY:.*?\]/gi, '')
      .replace(/\[(?:COMPOUNDS|PEPTIDES):.*?\]/gi, '')
      .replace(/\[PRODUCT:.*?\]/gi, (match, slug) => slug)
      .replace(/\[PROTOCOL:.*?\]/gi, (match, slug) => slug)
      .replace(/##\s+/g, '') // strip hashes but keep text
      .replace(/\*\*/g, ''); // strip bold marks for standard rendering

    const lines = cleanText.split('\n');

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50, 60, 70);

    lines.forEach(line => {
      let currentLine = line.trim();
      if (!currentLine) {
        y += 4; // empty line
        return;
      }

      // Check if line is a header (was ##)
      if (line.startsWith('## ') || line.match(/^[A-Z0-9\s]+:$/)) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 54, 102);
      } else {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 70, 80);
      }

      // Handle bullets
      if (currentLine.startsWith('- ') || currentLine.startsWith('* ')) {
        currentLine = "• " + currentLine.substring(2);
      }

      const splitLine = doc.splitTextToSize(currentLine, pageWidth - 40);
      
      if (y + (splitLine.length * 5) > pageHeight - 30) {
        addFooter();
        doc.addPage();
        pageCount++;
        addHeader(false);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 70, 80);
      }

      doc.text(splitLine, 20, y);
      y += (splitLine.length * 5) + 2;
    });

    y += 12; // Space between messages
  });

  addFooter();
  doc.save(`Atlas_Clinical_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}
